const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}
const E=ctx.EscapeEngine;
function fresh(){const g=new E(12345);g.state.mode='playing';g.state.monsters=[];return g;}
const g=fresh();assert.equal(g.packSize(),8,'backpack must start with eight slots');assert.equal(g.state.player.equipped.main,'normal');
// Low-level equipment mutation preserves wear; player action timing is covered in mine5.gameplay.test.cjs.
g.state.bag={torch:2};g.state.ore=0;
for(const id of ['light','heavy','magic','sword','shield','helmet','lamp','eye','anchor','lodestone','bellows']){
 const h=fresh();h.state.bag={torch:2};h.state.ore=0;assert.equal(h.acquireEquipment(id),true,id);const def=E.EQUIPMENT[id];assert.equal(h.equipGear(def.slot,id),true);assert.equal(h.state.turn,0);if(id==='sword')assert.equal(h.hasHand('torch'),false);if(id==='shield')assert.equal(h.hasHand('sword'),false);
}
g.acquireEquipment('heavy');g.state.player.dur=31;g.equipGear('main','heavy');g.state.player.dur=17;g.equipGear('main','normal');assert.equal(g.state.player.dur,31);g.equipGear('main','heavy');assert.equal(g.state.player.dur,17);assert.equal(g.equipGear('off','heavy'),false);
const a=fresh();a.state.bag={};a.state.ore=0;a.acquireEquipment('anchor');a.state.player.armor=1;a.equipGear('body','anchor');a.state.player.armor=2;a.equipGear('body','clothes');assert.equal(a.state.player.armor,1);a.equipGear('body','anchor');assert.equal(a.state.player.armor,2);assert.equal(a.packSize(),8);
const b=fresh();b.state.bag={};b.state.ore=0;b.acquireEquipment('lodestone');b.equipGear('body','lodestone');b.state.ore=120;b.state.bag={bread:b.itemMax('bread')*7};assert.ok(b.slots()<=8);assert.equal(b.equipGear('body','clothes'),false,'cannot overflow after losing magnetic storage');assert.equal(b.state.player.equipped.body,'lodestone');
const c=fresh();c.state.bag={};c.state.ore=0;c.acquireEquipment('sword');c.acquireEquipment('shield');c.equipGear('off','shield');const enemy=c.createMonster('skeleton',c.state.player.x+1,c.state.player.y,991);c.state.monsters=[enemy];c.monsterHit(enemy);assert.equal(c.ownsGear('shield'),true);assert.equal(c.state.player.equipped.off,'shield');assert.equal(c.state.player.inventoryGear.shield.dur,5);assert.equal(c.ownsGear('sword'),true);
const effects=fresh();effects.state.bag={torch:1};effects.state.ore=0;effects.acquireEquipment('lamp');effects.acquireEquipment('eye');effects.equipGear('off','lamp');assert.equal(effects.lightRadius(),5+effects.state.params.vision);assert.equal(effects.senseBonus(),2);effects.equipGear('off',null);effects.equipGear('head','eye');assert.equal(effects.state.player.gear.lamp,false);assert.equal(effects.state.player.gear.eye,true);assert.equal(effects.senseBonus(),0);
const miner=fresh();miner.state.bag={};miner.state.ore=0;miner.acquireEquipment('light');miner.acquireEquipment('heavy');miner.acquireEquipment('magic');miner.equipGear('main','heavy');assert.equal(miner.digHits({kind:'hard'}),1);const loud=miner.digNoise(6);miner.equipGear('main','light');assert.ok(miner.digNoise(3)<loud);assert.ok(miner.digHits({kind:'hard'})>=1);miner.equipGear('main','magic');miner.state.player.x=30;miner.state.player.y=30;Object.assign(miner.tile(31,30),{kind:'ore',cracks:0,items:{},gate:null,tidal:false});assert.equal(miner.act({type:'move',dx:1,dy:0}),true);assert.equal(miner.amount('ore'),3);assert.equal(miner.state.player.dur,159);
const full=fresh();full.state.bag={bread:full.itemMax('bread')*8};full.state.ore=0;full.acquireEquipment('heavy');assert.equal(full.slots(),8);assert.equal(full.equipGear('main','heavy'),true);assert.equal(full.slots(),8);assert.equal(full.equipGear('body',null),true);full.state.bag={};full.state.player.dur=12;full.equipGear('main','normal');assert.equal(full.dropGear('heavy'),true);assert.equal(full.takeGroundGear(0),true);full.equipGear('main','heavy');assert.equal(full.state.player.dur,12);assert.equal(full.state.turn,0);
console.log('Equipment checks passed: eight slots, category restrictions, independent wear, exclusive effects, safe capacity, shield wear.');