const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');const html=fs.readFileSync(process.env.MINE5_HTML||path.join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function game(seed=12345){const g=new E(seed);g.enableCards();g.startExpedition(g.campaign.preparedIds);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);g.state.mode='playing';g.state.monsters=[];g.state.params.hazardStart=999999;g.tick=function(n=1){this.state.turn+=n;};g.state.ore=50;return g;}
function visit(g,kind){let a=g.state.sites.find(a=>a.npcKind===kind);if(!a){const model=g.state.sites.find(a=>a.npcKind);a={...model,id:'test-'+kind,npcKind:kind,name:E.NPCS[kind].name,done:false,uses:1,offers:[]};g.state.sites.push(a);}g.state.player.x=a.x;g.state.player.y=a.y;a.discovered=true;g.state.npcId=a.id;return a;}
function rescue(g,kind){const a=g.state.sites.find(a=>a.id==='miner');g.state.player.x=a.x;g.state.player.y=a.y;a.discovered=true;a.done=false;a.rescueCase=kind;g.state.companion=null;return a;}
test('each floor has merchant, one special and two helpers on reachable safe spaced floor',()=>{const g=game(),s=g.state,list=s.sites.filter(a=>a.npcKind),home=s.sites.find(a=>a.id==='home'),reach=g.reachSet(home.x,home.y);assert.equal(list.length,4);assert.equal(list.filter(a=>['fortune','prosperity','longevity'].includes(a.npcKind)).length,1);assert.equal(list.find(a=>a.npcKind==='merchant').offers.length,6);for(const a of list){assert(reach.has(a.x+','+a.y));assert.equal(g.tile(a.x,a.y).kind,'floor');assert(!g.tile(a.x,a.y).fog);assert(s.sites.filter(b=>b!==a).every(b=>Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y))>=4));}g.seedNpcs();assert.equal(s.sites.filter(a=>a.npcKind).length,4);});
test('merchant full pack does not debit, successful purchase is once, and duplicate gear is rejected',()=>{const g=game(),a=visit(g,'merchant'),o=a.offers[0];while(g.countSlots()<15)g.receiveCard(g.makeCard('bread'));const ore=g.amount('ore');assert.equal(g.executeNpc('offer:'+o.id),false);assert.equal(g.amount('ore'),ore);assert.equal(o.remaining,1);g.state.expedition.cards=g.state.expedition.cards.filter(c=>c.type!=='supply');assert(g.executeNpc('offer:'+o.id));assert.equal(g.amount('ore'),ore-o.cost);assert.equal(o.remaining,0);assert.equal(g.executeNpc('offer:'+o.id),false);const gear=a.offers.find(o=>o.card.type==='gear');assert(g.receiveCard(g.makeCard(gear.card.id)));assert.equal(g.npcCheck('offer:'+gear.id).ok,false);});
test('selling is explicit, whole-card quantity priced, cannot sell equipped gear or repeat',()=>{const g=game(),a=visit(g,'merchant'),c=g.makeCard('bandage',3);g.receiveCard(c);const before=g.amount('ore');assert(g.executeNpc('sell:'+c.uid));assert.equal(g.amount('ore'),before+3);assert.equal(g.executeNpc('sell:'+c.uid),false);assert.equal(a.purse,15);assert.equal(g.npcCheck('sell:'+g.state.expedition.cards.find(c=>c.type==='gear').uid).ok,false);});
test('fortune shows three fixed gifts and locks all alternatives after one selection',()=>{const g=game(),a=visit(g,'fortune'),rng=g.rngFor('test-fortune');a.offers=[0,1,2].map(i=>g.makeNpcOffer('fortune',i,rng));const ore=g.amount('ore');assert(g.executeNpc('offer:o0'));assert.equal(g.amount('ore'),ore);assert.equal(g.executeNpc('offer:o1'),false);assert(a.done);});
test('prosperity cash is once and bounty only pays for a future elite once',()=>{const g=game(),a=visit(g,'prosperity');let ore=g.amount('ore');assert(g.executeNpc('cash'));assert.equal(g.amount('ore'),ore+6);assert.equal(g.executeNpc('cash'),false);a.done=false;a.uses=1;const m=g.createMonster('skeleton',a.x+1,a.y,9876);m.elite=true;g.state.monsters=[m];assert(g.executeNpc('bounty'));ore=g.amount('ore');g.killMonster(m);assert.equal(g.amount('ore'),ore+10);g.killMonster(m);assert.equal(g.amount('ore'),ore+10);assert(g.npcState().bounty.paid);});
test('longevity offers max life and healing, caps ten and consumes choice only once',()=>{const g=game(),a=visit(g,'longevity');g.state.player.maxHp=9;g.state.player.hp=1;assert(g.executeNpc('vitality'));assert.equal(g.state.player.maxHp,10);assert.equal(g.state.player.hp,10);assert.equal(g.executeNpc('heal'),false);a.done=false;a.uses=1;assert.equal(g.executeNpc('vitality'),false);g.state.player.hp=9;assert(g.executeNpc('heal'));assert.equal(g.state.player.hp,10);});
test('doctor healing and lamplighter fuel reject wasted payments and have limited uses',()=>{const g=game(),doctor=visit(g,'doctor');doctor.uses=2;g.state.player.hp=g.state.player.maxHp;let ore=g.amount('ore');assert.equal(g.executeNpc('heal'),false);assert.equal(g.amount('ore'),ore);g.state.player.hp=1;assert(g.executeNpc('heal'));assert.equal(g.state.player.hp,4);const light=visit(g,'lamplighter');g.state.expedition.torchDur=2;assert(g.executeNpc('fuel'));assert.equal(g.lightDurability('torch'),100);assert(light.done);});
test('mapper reveals actual exit terrain but never live monster visibility',()=>{const g=game();visit(g,'mapper');const exit=g.state.sites.find(a=>a.exitRole);exit.discovered=false;g.tile(exit.x,exit.y).seen=false;assert(g.executeNpc('map'));assert(g.state.sites.filter(a=>a.exitRole).some(a=>a.discovered&&g.tile(a.x,a.y).seen));});
test('scavenger full pack is atomic and allows replacement when input card is emptied',()=>{const g=game(),a=visit(g,'scavenger');a.offers=[{id:'trade',input:'bread',inputQty:1,card:g.makeCard('bandage',2),cost:0,remaining:1}];g.state.expedition.cards=g.state.expedition.cards.filter(c=>c.id!=='bread');g.receiveCard(g.makeCard('bread',2));while(g.countSlots()<15)g.receiveCard(g.makeCard('rune'));assert.equal(g.executeNpc('offer:trade'),false);assert.equal(g.amount('bread'),2);g.setAmount('bread',1);assert(g.executeNpc('offer:trade'));assert.equal(g.amount('bread'),0);assert.equal(g.amount('bandage'),2);assert.equal(g.countSlots(),15);});
test('injured requires bread or bandage; trapped requires pick durability; lost needs escort',()=>{const g=game();rescue(g,'injured');g.setAmount('bread',0);assert.equal(g.choose('rescue'),false);g.receiveCard(g.makeCard('bandage',1));assert(g.choose('rescue-bandage'));assert.equal(g.state.companion.rescueCase,'injured');assert.equal(g.amount('bandage'),0);rescue(g,'trapped');g.state.player.dur=7;assert.equal(g.choose('rescue-dig'),false);g.state.player.dur=20;const t=g.state.turn;assert(g.choose('rescue-dig'));assert.equal(g.state.player.dur,12);assert.equal(g.state.turn,t+2);rescue(g,'lost');assert(g.choose('rescue-walk'));assert.equal(g.state.companion.npcReward.ore,4);});
test('rescue reward waits for delivery, falls on ground when full, and cannot be duplicated',()=>{const g=game();rescue(g,'trapped');assert(g.choose('rescue-dig'));assert.equal(g.amount('repairKit'),0);while(g.countSlots()<15)g.receiveCard(g.makeCard('rune'));g.shelterCompanion();assert.equal(g.state.companion,null);assert.equal(g.groundCards().filter(c=>c.id==='repairKit').length,1);assert.equal(g.state.flags.rescued,1);g.shelterCompanion();assert.equal(g.groundCards().filter(c=>c.id==='repairKit').length,1);});
test('NPC state survives save, and legacy save migration adds encounters only once',()=>{const g=game(),a=visit(g,'merchant');assert(g.executeNpc('offer:'+a.offers[0].id));const save=JSON.parse(JSON.stringify(g.exportCampaign())),h=new E(4);assert(h.restoreCampaign(save));assert.equal(h.state.sites.find(x=>x.id===a.id).offers[0].remaining,0);delete save.state.npcState;save.state.sites=save.state.sites.filter(a=>!a.npcKind);const miner=save.state.sites.find(a=>a.id==='miner');delete miner.rescueCase;miner.done=true;assert(h.restoreCampaign(save));assert.equal(h.state.sites.filter(a=>a.npcKind).length,4);assert(h.state.sites.find(a=>a.id==='miner').rescueRewarded);h.seedNpcs();assert.equal(h.state.sites.filter(a=>a.npcKind).length,4);});
test('mineral exchange delegates wallet API only while near a merchant',()=>{const g=game(),a=visit(g,'merchant');E.MINERALS={ore:{name:'银矿',value:1},gold:{name:'金矿',value:4}};let gold=2;g.mineralAmount=id=>id==='gold'?gold:0;g.exchangeMineral=(id,n)=>{if(id!=='gold'||n>gold)return false;gold-=n;g.setAmount('ore',g.amount('ore')+n*4);return true;};const ore=g.amount('ore');assert(g.executeNpc('exchange:gold:1'));assert.equal(g.amount('ore'),ore+4);g.state.player.x=a.x+5;assert.equal(g.executeNpc('exchange:gold:all'),false);assert.equal(gold,1);});

test('full-pack escort reward arrives at next-floor entrance exactly once during departure',()=>{const g=game();rescue(g,'trapped');assert(g.choose('rescue-dig'));while(g.countSlots()<15)g.receiveCard(g.makeCard('rune'));const s=g.state,exit=s.sites.find(a=>a.id==='water');exit.discovered=true;s.player.x=exit.x;s.player.y=exit.y;s.companion.x=exit.x;s.companion.y=exit.y;s.routeChoice=exit.id;s.panel='route';assert(g.exitCheck().ok);assert(g.choose('depart'));assert.equal(s.depth,2);assert.equal(g.groundCards().filter(c=>c.id==='repairKit').length,1);assert.equal(s.npcTransitRewards.length,0);assert.equal(g.amount('repairKit'),0);const reward=g.groundCards().find(c=>c.id==='repairKit');s.mode='playing';const disposable=g.carriedCards().find(c=>c.type==='supply');g.dropCard(disposable.uid);assert(g.takeCard(reward.uid));assert.equal(g.amount('repairKit'),1);g.shelterCompanion();assert.equal(g.amount('repairKit'),1);});
test('stun does not advance time or block free merchant sale and mineral exchange',()=>{const g=game(),a=visit(g,'merchant');g.tick=Object.getPrototypeOf(g).tick.bind(g);const s=g.state;s.player.stun=1;const c=g.makeCard('glow');g.receiveCard(c);const turn=s.turn,ore=s.ore;assert.equal(g.act({type:'choose',kind:'npc:sell:'+c.uid}),true);assert.equal(s.turn,turn);assert.equal(s.player.stun,1);assert.equal(s.ore,ore+2);g.addMineral('gold',2);assert.equal(g.act({type:'choose',kind:'npc:exchange:gold:all'}),true);assert.equal(g.mineralAmount('gold'),0);assert.equal(s.turn,turn);assert.equal(s.player.stun,1);});
test('merchant does not sell a second copy of equipment already stored in camp',()=>{const g=game(),a=visit(g,'merchant'),id='heavy';g.campaign.stock.push(g.makeCard(id));a.offers=[{id:'unique',card:g.makeCard(id),cost:7,remaining:1}];const ore=g.state.ore;assert.equal(g.npcCheck('offer:unique').ok,false);assert.equal(g.act({type:'choose',kind:'npc:offer:unique'}),false);assert.equal(g.state.ore,ore);assert.equal(a.offers[0].remaining,1);});
