const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const html=fs.readFileSync(process.env.MINE5_HTML||'D:/MY_Blog/source/game/魏晋事业/mine5.html','utf8');
const ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx)}
const E=ctx.EscapeEngine,G=E.GEN;
function distances(l){const d=new Int32Array(l.size*l.size).fill(-1),q=[l.start.y*l.size+l.start.x];d[q[0]]=0;for(let i=0;i<q.length;i++){const id=q[i];for(const next of [id-1,id+1,id-l.size,id+l.size])if(next>=0&&next<d.length&&d[next]<0&&G.passableKind(l.tiles[next].kind)){d[next]=d[id]+1;q.push(next)}}return {d,max:Math.max(...d)}}
test('180 maps have unique scenes, random safe camps and BFS separated three exits',()=>{const starts=new Set(),layouts=new Set();for(const seed of [1,17,12345])for(let n=0;n<3;n++){const l=G.layoutChapter(seed,n,[]);assert.equal(l.size,180);assert.ok(l.regions.length>=18&&l.regions.length<=24);assert.equal(new Set(l.regions.map(r=>r.id)).size,l.regions.length);assert.deepEqual(Array.from(l.problems),[]);assert.equal(l.sites.filter(a=>a.id==='home').length,1);const home=l.sites.find(a=>a.id==='home');assert.equal(home.x,l.start.x);assert.equal(home.y,l.start.y);starts.add(home.x+','+home.y);layouts.add(l.regions.map(r=>r.cx+','+r.cy).join(';'));const {d,max}=distances(l);const exits=['mechanical','water','random-exit'].map(id=>l.sites.find(a=>a.id===id));assert.ok(exits.every(Boolean));assert.deepEqual(exits.map(a=>a.exitRole),['near','far','random']);for(const a of exits)assert.ok(d[a.y*l.size+a.x]>=0);const near=d[exits[0].y*l.size+exits[0].x],far=d[exits[1].y*l.size+exits[1].x];assert.ok(near>=45&&near<=75,'near '+near);assert.ok(far>=max*.75,'far '+far+'/'+max);for(let i=0;i<3;i++)for(let j=0;j<i;j++)assert.ok(Math.abs(exits[i].x-exits[j].x)+Math.abs(exits[i].y-exits[j].y)>=12);assert.ok(l.monsters.every(m=>Math.abs(m.x-home.x)+Math.abs(m.y-home.y)>=12));assert.ok(l.hazardCells.every(([x,y])=>Math.abs(x-home.x)+Math.abs(y-home.y)>=10));assert.ok(l.stats.walkRatio>=.15&&l.stats.walkRatio<=.5);const signatures=l.regions.map(r=>{let shape='';for(let y=r.cy-r.ry-1;y<=r.cy+r.ry+1;y++)for(let x=r.cx-r.rx-1;x<=r.cx+r.rx+1;x++)shape+=G.passableKind(l.tiles[y*l.size+x]?.kind)?'1':'0';return (r.rx+','+r.ry+':')+shape});assert.equal(new Set(signatures).size,l.regions.length)}assert.equal(starts.size,9);assert.equal(layouts.size,9)});
test('all chapter devices and cart retain reachable routes on enlarged maps',()=>{for(const seed of [17,12345])for(let n=0;n<3;n++){const g=new E(seed);if(n)g.load(n);const s=g.state,reach=g.reachSet(s.player.x,s.player.y);for(const a of s.sites.filter(a=>a.chapterDevice||['home','miner','workshop','pump','shrine','mechanical','water','random-exit'].includes(a.id)))assert.ok(g.standingNear(reach,a),seed+'/'+n+'/'+a.id);if(n===0)assert.ok(s.challenge.path.length>=8);if(n===2){s.mode='playing';s.turn=8;g.adventureTurn();const wetReach=g.reachSet(s.player.x,s.player.y);for(const a of s.sites.filter(a=>a.exitRole||a.chapterDevice))assert.ok(g.standingNear(wetReach,a),'high tide '+a.id)}}});

test('organic caves vary in scale and retain immutable interior pillars and sparse side caches',()=>{for(let n=0;n<3;n++){const l=G.layoutChapter(17,n,[]),areas=l.regions.map(r=>r.rx*r.ry),pillars=l.tiles.filter(t=>t.pillar),caches=l.sites.filter(a=>a.id.startsWith('scene-cache-'));assert.ok(Math.max(...areas)/Math.min(...areas)>=3,'caves need distinct small/large scales');assert.ok(pillars.length>=20,'interior pillar groups');assert.ok(pillars.every(t=>t.kind==='wall'&&!t.masonry),'pillars must bypass mining/bomb/ruin shortcuts');assert.ok(caches.length>=4&&caches.length<=7,'exploration does not guarantee a chest in every scene');assert.ok(caches.every(a=>Math.abs(a.x-l.regions[a.region].cx)+Math.abs(a.y-l.regions[a.region].cy)>=5),'caches sit off-center');const widths=new Set();for(let y=2;y<178;y++)for(let x=2;x<178;x++){if(!G.passableKind(l.tiles[y*180+x].kind))continue;let count=0;for(let dx=-3;dx<=3;dx++)if(G.passableKind(l.tiles[y*180+x+dx].kind))count++;widths.add(count);}assert.ok(widths.size>=5,'variable passage cross-sections');}});
test('mining, bombs and elite stone breaking cannot destroy generated pillars',()=>{const g=new E(17),s=g.state,entry=s.map.tiles.map((t,i)=>({t,i})).find(p=>p.t.pillar);assert.ok(entry,'has pillar');const x=entry.i%180,y=Math.floor(entry.i/180);assert.equal(g.eliteBreak(x,y),false);g.explode({x,y});assert.equal(entry.t.kind,'wall');const neighbor=[[1,0],[0,1],[-1,0],[0,-1]].find(([dx,dy])=>g.passable(x+dx,y+dy));if(neighbor){s.player.x=x+neighbor[0];s.player.y=y+neighbor[1];s.monsters=[];const before=s.turn;g.act({type:'move',dx:-neighbor[0],dy:-neighbor[1]});assert.equal(entry.t.kind,'wall');assert.equal(s.turn,before);}});

test('pillar groups survive generated side-route setup and high tide on additional seeds',()=>{for(const seed of [42,999])for(let n=0;n<3;n++){const g=new E(seed);if(n)g.load(n);const s=g.state;assert.ok(s.map.tiles.filter(t=>t.pillar).every(t=>t.kind==='wall'),'pillar overwritten by setup '+seed+'/'+n);if(n===2){s.mode='playing';s.turn=8;g.adventureTurn();assert.ok(s.map.tiles.filter(t=>t.pillar).every(t=>t.kind==='wall'),'pillar overwritten by tide '+seed);}}});
