const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});
for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}
const E=ctx.EscapeEngine;
function fresh(){const g=new E(12345);g.state.monsters=[];return g;}
function arena(g){g.state.mode='playing';g.state.player.x=30;g.state.player.y=30;for(let y=28;y<34;y++)for(let x=28;x<34;x++)Object.assign(g.tile(x,y),{kind:'floor',gate:null,tidal:false,items:{},cracks:0});}
// Duplicate spawns must disappear without removing consumable supplies or optional rewards.
test('each equipment type has one source across all three chapters',()=>{for(const seed of [1,12345,67890]){const g=new E(seed),seen=new Set(['normal','clothes']);let quests=0,breadSources=0;for(let n=0;n<3;n++){if(n)g.load(n);for(const a of g.state.sites){for(const raw of a.equipment||[]){const id=raw==='pick'?'magic':raw;assert.equal(seen.has(id),false,'duplicate '+id+' in chapter '+n);seen.add(id);}if(a.quest){quests++;assert.equal(n,0);assert.equal(a.id,'workshop');}if(a.container?.bread)breadSources++;}assert.equal(g.state.sites.find(a=>a.id==='risk-cache').equipment.length,1);}assert.equal(quests,1);assert.ok(breadSources>3);assert.equal(seen.size,13);}});
test('claimed equipment does not return after dropping or loading another chapter',()=>{const g=fresh();arena(g);g.acquireEquipment('heavy');assert.equal(g.dropGear('heavy'),true);assert.equal(g.acquireEquipment('heavy'),false);assert.equal(g.takeGroundGear(0),true);g.acquireEquipment('shield');assert.equal(g.acquireEquipment('shield'),false);g.load(1);assert.equal(g.state.sites.some(a=>a.equipment?.includes('shield')),false);});
test('quest part can be collected once and does not reappear on a chapter reload',()=>{const g=fresh(),s=g.state,a=s.sites.find(a=>a.id==='workshop');s.mode='playing';s.player.x=a.x;s.player.y=a.y;a.searched=true;s.lootId=a.id;assert.equal(g.loot('quest'),true);assert.equal(g.loot('quest'),false);assert.equal(s.local.part,true);assert.equal(a.quest,null);g.load(0);assert.equal(g.state.sites.some(a=>a.quest),false);assert.equal(g.state.local.part,true);g.load(1);assert.equal(g.state.local.part,false);});
// Repairs must change only the selected item, including unequipped items, at the normal price/time.
test('repair a spare pick without switching or repairing the active pick',()=>{const g=fresh(),p=g.state.player;g.state.ore=30;g.acquireEquipment('heavy');p.inventoryGear.heavy.dur=10;p.dur=40;const price=g.cost('repair');assert.equal(g.act({type:'buy',item:'repair:heavy'}),true);assert.equal(p.inventoryGear.heavy.dur,80);assert.equal(p.dur,40);assert.equal(p.equipped.main,'normal');assert.equal(g.state.ore,30-price);assert.equal(g.state.turn,2);});
test('repair a stored sword and spare armor without equipping them',()=>{const g=fresh(),p=g.state.player;g.state.ore=30;g.acquireEquipment('sword');p.swordDur=5;p.inventoryGear.sword.dur=5;g.acquireEquipment('anchor');p.inventoryGear.anchor.armor=0;assert.equal(g.act({type:'buy',item:'repair:sword'}),true);assert.equal(p.swordDur,45);assert.equal(p.equipped.off,'torch');assert.equal(g.act({type:'buy',item:'repair:anchor'}),true);assert.equal(p.inventoryGear.anchor.armor,6);assert.equal(p.armor,3);assert.equal(p.equipped.body,'clothes');assert.equal(g.state.turn,4);});
test('repair active gear clamps at maximum and persists through switching',()=>{const g=fresh(),p=g.state.player;g.state.ore=30;g.acquireEquipment('heavy');p.dur=200;assert.equal(g.act({type:'buy',item:'repair:normal'}),true);assert.equal(p.dur,220);g.equipGear('main','heavy');g.equipGear('main','normal');assert.equal(p.dur,220);});
test('invalid, full, unaffordable and late repairs spend nothing',()=>{const g=fresh();for(const id of ['normal','sword','torch','missing']){const ore=g.state.ore,turn=g.state.turn;assert.equal(g.act({type:'buy',item:'repair:'+id}),false);assert.equal(g.state.ore,ore);assert.equal(g.state.turn,turn);}g.state.player.dur=10;g.state.ore=0;assert.equal(g.act({type:'buy',item:'repair:normal'}),false);g.state.ore=20;g.state.campDeadline=g.state.turn+2;assert.equal(g.act({type:'buy',item:'repair:normal'}),false);assert.equal(g.state.ore,20);assert.equal(g.state.player.dur,10);g.state.campDeadline=null;g.state.mode='playing';assert.equal(g.act({type:'buy',item:'repair:normal'}),false);assert.equal(g.state.turn,0);});
test('magic pick uses one durability for ore but two for ordinary rock',()=>{const g=fresh();arena(g);g.acquireEquipment('magic');g.equipGear('main','magic');g.state.bag={};g.state.ore=0;g.tile(31,30).kind='ore';assert.equal(g.act({type:'move',dx:1,dy:0}),true);assert.equal(g.state.player.dur,159);assert.equal(g.state.ore,3);g.tile(32,30).kind='rock';assert.equal(g.act({type:'move',dx:1,dy:0}),true);assert.equal(g.state.player.dur,157);assert.equal(g.state.ore,3);});

test('unique shield blocks six hits, remains broken and can be repaired at the bench',()=>{const g=fresh();arena(g);const p=g.state.player;g.acquireEquipment('shield');g.equipGear('off','shield');const hp=p.hp,armor=p.armor;for(let i=0;i<6;i++){const m=g.createMonster('skeleton',31,30,990+i);g.state.monsters=[m];g.monsterHit(m);assert.equal(g.state.monsters.length,1);assert.equal(m.hp,2);assert.equal(p.inventoryGear.shield.dur,5-i);assert.equal(p.hp,hp);assert.equal(p.armor,armor);}assert.equal(g.ownsGear('shield'),true);assert.equal(p.equipped.off,'shield');assert.equal(g.hasHand('shield'),false);const m=g.createMonster('skeleton',31,30,995);g.state.monsters=[m];g.monsterHit(m);assert.equal(g.state.monsters.length,1);assert.ok(p.hp<hp||p.armor<armor);g.equipGear('off','torch');g.state.mode='home';g.state.ore=20;assert.equal(g.act({type:'buy',item:'repair:shield'}),true);assert.equal(p.inventoryGear.shield.dur,6);assert.equal(p.equipped.off,'torch');g.equipGear('off','shield');assert.equal(g.hasHand('shield'),true);g.load(1);assert.equal(p.inventoryGear.shield.dur,6);assert.equal(g.state.sites.some(a=>a.equipment?.includes('shield')),false);});

test('each chapter yields its advertised unique reward and stops the risk timer',()=>{const g=fresh();for(let n=0;n<3;n++){if(n)g.load(n);const s=g.state,a=s.sites.find(a=>a.id==='risk-cache'),id=g.chapterPlay().reward;s.mode='playing';s.monsters=[];s.player.x=a.x;s.player.y=a.y;a.searched=true;s.lootId=a.id;s.adventure.risk.due=10;assert.equal(g.loot('equipment:'+id),true,'chapter '+n+' reward '+id);assert.equal(g.ownsGear(id),true);assert.equal(s.adventure.risk.due,null);assert.equal(s.adventure.risk.secured,true);assert.equal(a.equipment.length,0);assert.ok(a.container.bomb>0);}});
