const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Million/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const TARGET=process.env.GAME_HTML||process.env.MINE5_HTML||'D:/MY_Blog/source/game/魏晋事业/mine5.html';
async function launch(t,viewport,touch=false){const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),p=await browser.newPage({viewport,reducedMotion:'reduce',hasTouch:touch}),errors=[];p.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();assert.deepEqual(errors,[]);});await p.addInitScript(()=>{let Engine;Object.defineProperty(window,'EscapeEngine',{get(){return Engine},set(E){Engine=new Proxy(E,{construct(T,args){const g=Reflect.construct(T,args.length?args:[12345]);window.__testGame=g;return g;}});}});});await p.goto(pathToFileURL(TARGET).href);p.setDefaultTimeout(5000);return p;}
async function fillHand(p){await p.evaluate(()=>{const g=__testGame;g.startExpedition(g.campaign.preparedIds);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.params.hazardStart=999999;s.expedition.cards=[];s.player.inventoryGear={};s.player.equipped={body:null,head:null,main:null,off:null};for(const id of ['elite_pick','elite_cloak','elite_hook']){if(!g.receiveCard(g.makeCard(id)))throw Error('receive '+id);if(!g.equipGear(EscapeEngine.ELITE_GEAR[id].slot,id))throw Error('equip '+id);}const ids=['bread','bomb','rope','rune','torch','quiet','glow','lureBell','smokeBottle','hastePotion','bandage','clearingPowder','repairKit','lampOil','elite_tide'];for(const id of ids)if(!g.receiveCard(g.makeCard(id,3)))throw Error('receive '+id);g.syncEquipment();if(document.querySelector('#dialog').open)document.querySelector('#dialog').close();});await refresh(p);}
async function refresh(p){await p.locator('#world').focus();await p.keyboard.press('z');await p.keyboard.press('z');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function geometry(p){return p.evaluate(()=>['#world','.player-panel','#task-button'].map(sel=>{const r=document.querySelector(sel).getBoundingClientRect();return[r.x,r.y,r.width,r.height];}));}
async function hitPoint(p,uid){return p.evaluate(uid=>{const b=document.querySelector('[data-card-select="'+uid+'"]'),r=b.getBoundingClientRect();for(let y=Math.max(1,r.y+4);y<Math.min(innerHeight,r.bottom-2);y+=5)for(let x=Math.max(1,r.x+4);x<Math.min(innerWidth,r.right-2);x+=4)if(document.elementFromPoint(x,y)?.closest('[data-card-select]')===b)return{x,y};return null;},uid);}

async function checkHand(p,count,side,touch=false){const info=await p.locator('#card-dock').evaluate(el=>({scroll:!!el.querySelector('.hand-scroll'),overflow:[el,...el.querySelectorAll('.hand-spread,.hand-row')].map(n=>({w:n.clientWidth,h:n.clientHeight,sw:n.scrollWidth,sh:n.scrollHeight,x:getComputedStyle(n).overflowX,y:getComputedStyle(n).overflowY})),columns:[...new Set([...el.querySelectorAll('[data-card-select]')].map(c=>c.dataset.handColumn))],rows:[...new Set([...el.querySelectorAll('[data-card-select]')].map(c=>c.dataset.handRow))],cards:[...el.querySelectorAll('[data-card-select]')].map(c=>({uid:c.dataset.cardSelect,r:c.getBoundingClientRect().toJSON()})),viewport:{w:innerWidth,h:innerHeight}}));assert.equal(info.scroll,false);assert.equal(info.cards.length,count);if(side){assert.equal(info.columns.length,1);assert(info.rows.length>=count);}for(const n of info.overflow){assert(n.sw<=n.w+1,JSON.stringify(n));assert(n.sh<=n.h+1,JSON.stringify(n));assert(!['scroll','auto'].includes(n.x)&&!['scroll','auto'].includes(n.y),JSON.stringify(n));}for(const c of info.cards)assert(c.r.left>=0&&c.r.top>=0&&c.r.right<=info.viewport.w+1&&c.r.bottom<=info.viewport.h+1,c.uid+JSON.stringify(c.r));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await p.evaluate(()=>{window.__dockClicks=[];if(!window.__dockClickTrace){window.__dockClickTrace=true;document.addEventListener('click',e=>{window.__dockClicks.push({text:e.target.textContent.slice(0,50),dataset:{...e.target.closest('button')?.dataset}});},true);}});for(const c of info.cards){await p.mouse.move(1,1);const point=await hitPoint(p,c.uid);assert(point,'exposed hit region: '+c.uid);if(side){await p.mouse.move(point.x,point.y);await p.waitForFunction(()=>!document.querySelector('#card-popover').hidden);const [pop,dock]=await Promise.all([p.locator('#card-popover').boundingBox(),p.locator('#card-dock').boundingBox()]);assert(pop.x+pop.width<=dock.x+1,'popover must stay left of side dock: '+JSON.stringify({pop,dock}));}if(touch)await p.touchscreen.tap(point.x,point.y);else await p.mouse.click(point.x,point.y);
if(c.uid.startsWith('ability:')){try{await p.waitForFunction(()=>!document.querySelector('#aim-bar').hidden);}catch(e){throw Error(JSON.stringify({uid:c.uid,point,clicks:await p.evaluate(()=>__dockClicks)}));}if(side)assert(await p.locator('#card-dock').isVisible(),'PC skill aiming keeps dock open');await p.locator('#cancel-aim').click();if(!(await p.locator('#card-dock').isVisible()))await p.locator('#card-tab').click();continue;}
try{await p.waitForFunction(uid=>document.querySelector('[data-card-select="'+uid+'"]').getAttribute('aria-pressed')==='true',c.uid);}catch(e){const trace=await p.evaluate(({uid,point})=>({uid,point,hit:document.elementFromPoint(point.x,point.y)?.closest('[data-card-select]')?.dataset.cardSelect,chosen:[...document.querySelectorAll('[data-card-select][aria-pressed="true"]')].map(b=>b.dataset.cardSelect),rect:document.querySelector('[data-card-select="'+uid+'"]')?.getBoundingClientRect().toJSON(),clicks:window.__dockClicks}),{uid:c.uid,point});throw Error(JSON.stringify(trace));}assert(await p.locator('#card-popover').isVisible());await p.locator('[data-card-dismiss]').click();}}

for(const vp of [{width:1280,height:900},{width:900,height:640}])test('single column fits all 18 cards, stable hover and a separate map '+vp.width,async t=>{const p=await launch(t,vp);await fillHand(p);const dock=p.locator('#card-dock');assert.equal(await dock.getAttribute('data-position'),'side');const info=await dock.evaluate(el=>({rect:el.getBoundingClientRect().toJSON(),scroll:el.scrollHeight,h:el.clientHeight,cards:[...el.querySelectorAll('[data-card-select]')].map(b=>({id:b.dataset.cardSelect,ability:!!b.dataset.abilityCard,column:b.dataset.handColumn,rect:b.getBoundingClientRect().toJSON()}))}));assert.equal(info.cards.length,18);assert(info.cards.every(b=>b.column==='0'));assert(info.scroll<=info.h+1);for(const c of info.cards)assert(c.rect.bottom<=vp.height&&c.rect.left>=info.rect.left);const map=await p.locator('#world').boundingBox();assert(map.x+map.width<info.rect.left,'card rail must not cover map');const base=await geometry(p),turn=await p.evaluate(()=>__testGame.state.turn);let previewTop;
for(const c of info.cards){await p.mouse.move(1,1);const pt=await hitPoint(p,c.id);assert(pt,c.id+' exposed');const before=await p.locator('[data-card-select="'+c.id+'"]').boundingBox();await p.mouse.move(pt.x,pt.y);await p.waitForFunction(()=>!document.querySelector('#card-popover').hidden);assert.deepEqual(await p.locator('[data-card-select="'+c.id+'"]').boundingBox(),before,'hover must not move card');const pop=await p.locator('#card-popover').boundingBox();assert(pop.x+pop.width<info.rect.left);if(previewTop===undefined)previewTop=pop.y;else assert(Math.abs(pop.y-previewTop)<2,'preview stays fixed');await p.mouse.click(pt.x,pt.y);if(c.ability){if(await p.locator('#aim-bar').isVisible())await p.locator('#cancel-aim').click();}else{assert.equal(await p.locator('[data-card-select="'+c.id+'"]').getAttribute('aria-pressed'),'true');await p.locator('[data-card-dismiss]').click();}}
assert.equal(await p.evaluate(()=>__testGame.state.turn),turn);assert.deepEqual(await geometry(p),base);await p.locator('[data-card-close]').click();assert.deepEqual(await geometry(p),base);await p.locator('#bag-button').click();assert.deepEqual(await geometry(p),base);await p.locator('[data-card-position]').click();assert.equal(await dock.getAttribute('data-position'),'bottom');assert((await p.locator('#world').boundingBox()).width>map.width);await p.locator('[data-card-position]').click();assert.deepEqual(await geometry(p),base);await p.reload();assert.equal(await dock.getAttribute('data-position'),'side');await p.mouse.move(1,1);await p.screenshot({path:path.join(process.env.TEMP,'mine5-column-'+vp.width+'.png')});});
test('two camp cards show their complete faces in one column',async t=>{const p=await launch(t,{width:1280,height:900});const cards=await p.locator('.hand-row [data-card-select]').evaluateAll(bs=>bs.map(b=>({r:b.getBoundingClientRect().toJSON(),hidden:getComputedStyle(b.querySelector('.card-art')).visibility})));assert.equal(cards.length,2);assert(cards.every(b=>b.hidden==='visible'));assert(cards[0].r.bottom<cards[1].r.top);});

test('mobile keeps collapsible bottom dock and all 18 cards usable',async t=>{const p=await launch(t,{width:390,height:844},true);assert.equal(await p.locator('#card-dock').isVisible(),false);await fillHand(p);const before=await geometry(p),turn=await p.evaluate(()=>__testGame.state.turn);assert.equal(await p.locator('#card-dock').isVisible(),false);await p.locator('#card-tab').click();assert.equal(await p.locator('#card-dock').getAttribute('data-position'),'bottom');assert.deepEqual(await geometry(p),before);assert.equal(await p.locator('[data-ability-card]').count(),3);await checkHand(p,18,false,true);assert.equal(await p.evaluate(()=>__testGame.state.turn),turn);await p.locator('[data-card-close]').click();assert.equal(await p.locator('#card-dock').isVisible(),false);assert.deepEqual(await geometry(p),before);});



