const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const ctx=vm.createContext({console});for(const m of fs.readFileSync(path.join(__dirname,'mine5.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function arena(){const g=new E(12345);g.enableCards();g.startExpedition(g.campaign.preparedIds,0,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.params.vision=0;s.player.x=30;s.player.y=30;s.player.facing=[1,0];for(const t of s.map.tiles){delete t.fixedLamp;t.torch=false;t.light=null;}for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',collapseAt:null});g.equipGear('head',null);s.visionCache=null;s.lightCache=null;return g;}
test('torch light has clear core, dim edge, terrain-only fringe and black beyond',()=>{const g=arena();assert.equal(g.lightLevel(33,30),3);assert.equal(g.lightLevel(34,30),2);assert.equal(g.lightLevel(35,30),1);assert.equal(g.lightLevel(36,30),0);assert.equal(g.visible().has('35,30'),false);assert.equal(g.terrainVisible().has('35,30'),true);assert.equal(g.lightLevel(28,30),3);});
test('unlit vision has three base rings; a headlamp extends only the forward cone',()=>{const g=arena();g.equipGear('off',null);assert.equal(g.lightLevel(31,30),3);assert.equal(g.lightLevel(32,30),2);assert.equal(g.lightLevel(33,30),1);assert.equal(g.lightLevel(34,30),0);g.equipGear('head','helmet');assert.equal(g.lightLevel(32,30),3);assert.equal(g.lightLevel(30,32),2);assert.equal(g.lightLevel(28,30),2);g.state.player.facing=[-1,0];assert.equal(g.lightLevel(28,30),3);});
test('terrain-only fringe never reveals a creature even with a locked attack',()=>{const g=arena(),m=g.createMonster('skeleton',35,30,100);g.state.monsters=[m];m.plan={kind:'melee',due:1,cells:[{x:30,y:30}]};assert.equal(g.monsterVisible(m),false);g.tile(32,30).kind='wall';g.state.visionCache=null;assert.equal(g.lightLevel(34,30),0);});
test('each elapsed turn burns equipped and placed light; inventory actions do not',()=>{const g=arena();assert.equal(g.lightDurability('torch'),100);g.act({type:'card-organize'});assert.equal(g.lightDurability('torch'),100);g.act({type:'wait'});assert.equal(g.lightDurability('torch'),99);g.equipGear('head','helmet');const before=g.lightDurability('helmet');g.tick(3);assert.equal(g.lightDurability('torch'),96);assert.equal(g.lightDurability('helmet'),before-3);});
test('placing a worn torch doubles its remaining fuel and removes directional restriction',()=>{const g=arena();g.tick(7);assert.equal(g.lightDurability('torch'),93);g.act({type:'light-place',item:'torch'});assert.equal(g.state.player.equipped.off,null);const t=g.tile(30,30);assert.equal(t.light.dur,185);assert.equal(t.light.max,200);assert.equal(g.lightLevel(28,30),3);t.light.dur=2;g.tick(2);assert.equal(t.torch,false);assert.equal(t.light.dur,0);assert.equal(g.lightLevel(32,30),2);});
test('hand lamp is brightest, wears down and retains fuel through save and extraction',()=>{const g=arena();g.acquireEquipment('lamp');assert.equal(g.equipGear('off','lamp'),true);assert.equal(g.lightRadius(),5);g.tick(2);assert.equal(g.lightDurability('lamp'),398);const save=JSON.parse(JSON.stringify(g.exportCampaign())),h=new E(1);h.enableCards();assert.equal(h.restoreCampaign(save),true);assert.equal(h.lightDurability('lamp'),398);h.settleExpedition(true);assert.equal(h.campaign.stock.find(c=>c.id==='lamp').data.dur,398);});
test('worn torches conserve per-unit fuel through stowing, merging and extraction',()=>{const g=arena();g.tick(4);g.equipGear('off',null);const c=g.carriedCards().find(c=>c.id==='torch');assert.deepEqual(Array.from(c.fuels),[96]);g.receiveCard(g.makeCard('torch',2));g.organizeCards();assert.deepEqual(Array.from(g.carriedCards().filter(c=>c.id==='torch').flatMap(c=>Array.from(c.fuels))).sort((a,b)=>a-b),[96,100,100]);g.equipGear('off','torch');g.tick();g.settleExpedition(true);const fuels=g.state.expedition.result.cards.filter(c=>c.id==='torch').flatMap(c=>Array.from(c.fuels));assert.equal(fuels.reduce((a,b)=>a+b,0),295);});
test('placed lamp doubles fuel and cannot be recovered even when extinguished',()=>{const g=arena();g.acquireEquipment('lamp');g.state.player.inventoryGear.lamp.dur=1;assert.equal(g.act({type:'light-place',item:'lamp'}),true);const t=g.tile(30,30);assert.equal(t.light.dur,1);assert.equal(t.light.max,800);g.tick();assert.equal(t.torch,false);assert.equal(g.act({type:'light-take'}),false);g.pickupAll();assert.equal(g.ownsGear('lamp'),false);assert.equal(t.light.dur,0);});
test('chosen torch stack keeps its own fuel when equipping from its card',()=>{const g=arena();g.equipGear('off',null);const c=g.makeCard('torch',2);c.fuels=[12,7];g.receiveCard(c);assert.equal(g.act({type:'equip-gear',slot:'off',item:'torch',cardUid:c.uid}),true);assert.equal(g.lightDurability('torch'),12);assert.deepEqual(Array.from(c.fuels),[7]);assert.equal(c.qty,1);});
test('old saves migrate hand lamps out of head slot and initialize missing fuel once',()=>{const g=arena();g.acquireEquipment('lamp');g.equipGear('off',null);g.state.player.equipped.head='lamp';delete g.state.player.inventoryGear.lamp.dur;for(const c of g.state.expedition.cards)delete c.fuels;const save=JSON.parse(JSON.stringify(g.exportCampaign())),h=new E(1);h.enableCards();assert.equal(h.restoreCampaign(save),true);assert.equal(h.state.player.equipped.head,null);assert.equal(h.state.player.equipped.off,'lamp');assert.equal(h.lightDurability('lamp'),400);h.tick();assert.equal(h.lightDurability('lamp'),399);});

test('legacy one-unit torch drop retains fuel when reclaimed as an unlit card',()=>{const g=arena();g.tick(10);assert.equal(g.act({type:'drop',item:'torch',amount:1}),true);const c=g.groundCards().find(c=>c.id==='torch');assert.deepEqual(Array.from(c.fuels),[90]);g.pickupAll();assert.equal(g.carriedCards().find(v=>v.uid===c.uid).fuels[0],90);});
