const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');const html=fs.readFileSync(process.env.GAME_HTML||process.env.MINE5_HTML||path.join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function game(n=0){const g=new E(12345);g.enableCards();g.startExpedition(g.campaign.preparedIds,n,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);g.state.mode='playing';g.state.monsters=[];g.state.bombs=[];g.state.hazards=[];g.state.params.hazardStart=999999;return g;}
function arena(){const g=game(),s=g.state,p=s.player;p.x=30;p.y=30;p.hp=p.maxHp=6;p.armor=0;p.inventoryGear.clothes.armor=0;for(let y=24;y<=38;y++)for(let x=24;x<=38;x++)Object.assign(g.tile(x,y),{kind:'floor',items:{},cards:[],equipment:[],collapseAt:null,tidal:false,gate:null,fog:null});s.lightCache=null;s.visionCache=null;return g;}
function near(g,id){const a=g.state.sites.find(a=>a.id===id);assert(a,id);a.discovered=true;g.state.player.x=a.x;g.state.player.y=a.y;return a;}
function quiet(g){g.tick=function(n=1){this.state.turn+=n;this.state.total+=n;this.challengeTurn();};return g;}
function plan(g,type,kind='melee'){const p=g.state.player,m=g.createMonster(type,p.x+1,p.y,999,[-1,0]);m.hp=8;m.alert=8;m.plan={kind,cells:[{x:p.x,y:p.y}],origin:{x:m.x,y:m.y},due:g.state.turn+1};g.state.monsters=[m];return m;}
test('walking over supplies never vacuums them into a new card while minerals still enter the wallet',()=>{const g=arena(),s=g.state;g.setAmount('bread',2);const slots=g.countSlots(),t=g.tile(31,30);t.items={bread:1,ore:2,gold:1};assert(g.act({type:'move',dx:1,dy:0}));assert.equal(g.amount('bread'),2,'supplies require explicit pickup');assert.equal(t.items.bread,1);assert.equal(g.countSlots(),slots);assert.equal(g.amount('ore'),2);assert.equal(g.mineralAmount('gold'),1);assert(g.pickupAll());assert.equal(g.amount('bread'),3);});
test('automatic collection refuses detached or remote item containers and preserves manual nearby loot',()=>{const g=arena(),remote=g.tile(33,30);remote.items={ore:3,iron:2,bread:1};assert.equal(g.collectItems(remote.items,true),false);assert.equal(g.amount('ore'),0);assert.equal(remote.items.iron,2);assert.equal(g.collectItems({ore:99},true),false);assert(g.collectItems(remote.items,false));assert.equal(g.amount('ore'),3);});
test('ground cards and equipment remain untouched by walking',()=>{const g=arena(),t=g.tile(31,30),c=g.makeCard('bandage',2);t.cards=[c];t.equipment=[{id:'sword',data:{dur:20}}];g.act({type:'move',dx:1,dy:0});assert.equal(g.amount('bandage'),0);assert.equal(g.ownsGear('sword'),false);assert.equal(t.cards[0].uid,c.uid);});
for(const [type,kind]of [['undead','melee'],['skeleton','melee'],['mud','melee'],['sentinel','sweep'],['beetle','shell']])test(type+' ordinary locked attack resolves against old cells after player movement',()=>{const g=arena(),m=plan(g,type,kind);assert.equal(g.isPriorityMelee(m),false);g.act({type:'move',dx:0,dy:1});assert.equal(g.state.player.hp,6);assert.equal(m.plan,null);assert.equal(m.actedAt,g.state.turn);});
test('swift trait is explicit and only swift melee attacks before movement',()=>{const g=arena(),m=plan(g,'bat');assert.equal(m.swift,true);assert.equal(E.MONSTER_BEHAVIOR.bat.swift,true);assert.equal(E.MONSTER_BEHAVIOR.rat.swift,true);assert.equal(g.isPriorityMelee(m),true);assert.match(g.monsterPlanLabel(m),/迅捷/);g.act({type:'move',dx:0,dy:1});assert.equal(g.state.player.hp,5);});
test('frost interrupts ordinary melee before harm, while swift lethal melee prevents consumption',()=>{for(const swift of [false,true]){const g=arena(),m=plan(g,swift?'bat':'undead');g.receiveCard(g.makeCard('rune',1));g.state.player.hp=1;g.act({type:'use',item:'rune'});assert.equal(g.state.player.hp,swift?0:1);assert.equal(g.amount('rune'),swift?1:0);if(!swift){assert(m.freeze>0);assert.equal(m.plan,null);}}});
test('cart needs real part and overhaul, then two off-track repair nodes',()=>{const g=quiet(game()),s=g.state,c=s.challenge;near(g,'cart-control');assert.equal(g.chapterActionCheck('chapter:start').ok,false);assert.equal(c.trackRepairs.length,2);s.local.part=true;g.setAmount('ore',3);assert(g.act({type:'choose',kind:'chapter:cart:repair-ore'}));assert.equal(g.amount('ore'),0);assert(c.overhauled);assert(g.act({type:'choose',kind:'chapter:start'}));for(const r of c.trackRepairs){const a=s.sites.find(a=>a.id===r.siteId);assert(a);assert.notDeepEqual({x:a.x,y:a.y},c.path[r.index]);const before=s.player.dur;near(g,a.id);assert(g.act({type:'choose',kind:'chapter:track:'+r.siteId}));assert.equal(s.player.dur,before-6);assert(r.fixed);}let guard=0;while(!c.complete&&guard++<c.path.length+5){s.player.x=c.cart.x;s.player.y=c.cart.y;g.tick();}assert(c.complete);});
test('unrepaired track actually blocks the cart and invalid resource actions are free',()=>{const g=quiet(game()),s=g.state,c=s.challenge,r=c.trackRepairs[0];c.started=true;c.overhauled=true;c.index=r.index-1;c.cart={...c.path[c.index]};s.player.x=c.cart.x;s.player.y=c.cart.y;g.challengeTurn();assert.equal(c.index,r.index-1);near(g,r.siteId);s.player.dur=5;const turn=s.turn;assert.equal(g.act({type:'choose',kind:'chapter:track:'+r.siteId}),false);assert.equal(s.turn,turn);assert.equal(s.player.dur,5);});
test('runes require six documented activations; mistakes roll back only current round and cost two turns',()=>{const g=quiet(game(1)),s=g.state,c=s.challenge;assert.equal(c.order.length,6);near(g,'city-inscription');g.act({type:'choose',kind:'chapter:read'});for(let i=0;i<4;i++){const id=c.order[c.progress];near(g,'rune-'+id);assert(g.act({type:'choose',kind:'chapter:rune:'+id}));}assert.equal(c.progress,4);const wrong=['hammer','lamp','wave'].find(id=>id!==c.order[c.progress]&&!s.sites.find(a=>a.id==='rune-'+id).done);near(g,'rune-'+wrong);const turn=s.turn;assert(g.act({type:'choose',kind:'chapter:rune:'+wrong}));assert.equal(c.progress,3);assert.equal(s.turn,turn+2);assert(s.notes.find(n=>n.id==='rune-order').text.includes(' → '));while(c.progress<6){const id=c.order[c.progress];near(g,'rune-'+id);assert(g.act({type:'choose',kind:'chapter:rune:'+id}));}assert(c.complete);});
test('river anchors consume real rope or silver before tide-gated two-stage sluices',()=>{const g=quiet(game(2)),s=g.state,c=s.challenge;assert.deepEqual(Object.keys(c.anchors),['a','b']);s.turn=8;near(g,'sluice-high');assert.equal(g.chapterActionCheck('chapter:sluice:high').ok,false);g.receiveCard(g.makeCard('rope',1));near(g,'river-anchor-a');assert(g.act({type:'choose',kind:'chapter:anchor:a:rope'}));assert.equal(g.amount('rope'),0);near(g,'sluice-high');s.turn=8;assert(g.act({type:'choose',kind:'chapter:sluice:high'}));g.setAmount('ore',3);near(g,'river-anchor-b');assert(g.act({type:'choose',kind:'chapter:anchor:b:ore'}));assert.equal(g.amount('ore'),0);near(g,'sluice-low');s.turn=16;assert(g.act({type:'choose',kind:'chapter:sluice:low'}));assert(c.complete);});
test('far and random exits remain optional-task bypasses, and new devices are reachable in both river phases',()=>{for(const n of [0,1,2]){const g=game(n),s=g.state;for(const id of ['water','random-exit']){near(g,id);s.routeChoice=id;assert(g.exitCheck().ok,id+' theme '+n);}for(const high of [false,true]){if(s.adventure.tide)for(const [x,y]of s.adventure.tide.cells)g.tile(x,y).kind=high?'water':'floor';const home=s.sites.find(a=>a.id==='home'),reach=g.reachSet(home.x,home.y);for(const a of s.sites.filter(a=>a.chapterDevice))assert(g.standingNear(reach,a),a.id+' phase '+high);}}});
