const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const html=fs.readFileSync(process.env.MINE5_HTML||process.argv[2]||require('node:path').join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function arena(seed=12345){const g=new E(seed);g.enableCards();g.startExpedition(g.campaign.preparedIds,0,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.params.vision=0;s.params.hazardStart=999999;s.player.x=30;s.player.y=30;s.player.facing=[1,0];s.environment.clouds=[];s.environment.cleared=[];for(const t of s.map.tiles){delete t.fixedLamp;t.torch=false;t.light=null;delete t.fog;}for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',collapseAt:null});s.visionCache=null;s.lightCache=null;return g;}
function give(g,id,qty=1){const c=g.makeCard(id,qty);assert(g.receiveCard(c));return c;}
function use(g,id,target){give(g,id);return g.act({type:'use',item:id,...(target?{target}:{})});}
test('12 items have unique art, names and functional descriptions; supplies retain quantities',()=>{assert.equal(Object.keys(E.COMMON_ITEMS).length,12);const g=arena();for(const [id,d]of Object.entries(E.COMMON_ITEMS)){const c=g.makeCard(id,3);assert(d.art.length>100);assert(d.text.length>10);assert.equal(c.type,d.type);if(d.type==='supply'){assert.equal(c.qty,3);assert(!E.CARDS[id]);assert(d.action);}else assert(E.CARDS[id]);}assert(html.includes('if(EscapeEngine.COMMON_ITEMS[c.id])return itemIcon(c.id)'));});
test('starter keeps only bread and kit prepared, 8 random extras, gear unique and all additions obtainable',()=>{const found=new Set(),g=new E(1);for(let seed=1;seed<=80;seed++){g.seed=seed;g.state.floorSeed=seed;g.enableCards();assert.equal(g.campaign.stock.length,10);assert.deepEqual(Array.from(g.campaign.stock.filter(c=>g.campaign.preparedIds.includes(c.uid)),c=>c.id),['bread','kit']);const gear=g.campaign.stock.filter(c=>c.type==='gear');assert.equal(new Set(gear.map(c=>c.id)).size,gear.length);for(const c of g.campaign.stock)found.add(c.id);}for(const id of Object.keys(E.COMMON_ITEMS))assert(found.has(id),id+' absent from starter pool');});
test('exploration supplies seed once in accessible ordinary containers per level',()=>{const g=new E(42);g.enableCards();g.startExpedition(g.campaign.preparedIds);const cards=()=>g.state.sites.flatMap(a=>a.cards||[]).filter(c=>E.COMMON_ITEMS[c.id]);assert(cards().length>0);const before=JSON.stringify(g.state.sites);g.seedCommonSupplies();assert.equal(JSON.stringify(g.state.sites),before);assert(!g.state.sites.find(a=>a.id==='risk-cache')?.cards?.some(c=>E.COMMON_ITEMS[c.id]));});
test('lure rings for 4 turns and invalid far throw neither consumes nor advances',()=>{const g=arena(),c=give(g,'lureBell',2),s=g.state,t=s.turn;assert.equal(g.act({type:'use',item:'lureBell',target:{x:44,y:30}}),false);assert.equal(c.qty,2);assert.equal(s.turn,t);assert(g.act({type:'use',item:'lureBell',target:{x:33,y:30}}));g.tick(3);assert.equal(s.noiseSeq,4);g.tick(2);assert.equal(s.noiseSeq,4);assert.equal(g.amount('lureBell'),1);});
test('smoke blocks light and sight while clearing powder creates temporary clear ground',()=>{const g=arena();assert(use(g,'smokeBottle',{x:32,y:30}));assert(g.fogAt(32,30)>0);assert(use(g,'clearingPowder'));assert.equal(g.fogAt(32,30),0);});
test('haste moves twice in one turn, stops at blockers, expires after four move actions',()=>{const g=arena();assert(use(g,'hastePotion'));const t=g.state.turn;assert(g.act({type:'move',dx:1,dy:0}));assert.equal(g.state.player.x,32);assert.equal(g.state.turn,t+1);g.tile(34,30).kind='wall';g.act({type:'move',dx:1,dy:0});assert.equal(g.state.player.x,33);g.act({type:'move',dx:0,dy:1});g.act({type:'move',dx:0,dy:1});assert.equal(g.commonEffects().haste,0);const y=g.state.player.y;g.act({type:'move',dx:0,dy:1});assert.equal(g.state.player.y,y+1);});
test('hardening reduces normal damage, never bypass damage, and expires',()=>{const g=arena();g.state.player.armor=0;assert(use(g,'hardeningPotion'));let hp=g.state.player.hp;g.hurt(1);assert.equal(g.state.player.hp,hp);g.hurt(1,true);assert.equal(g.state.player.hp,hp-1);g.tick(6);hp=g.state.player.hp;g.hurt(1);assert.equal(g.state.player.hp,hp-1);});
test('repair pack restores 70 pick durability and rejects full durability',()=>{const g=arena();g.state.player.dur=30;assert(use(g,'repairKit'));assert.equal(g.state.player.dur,100);g.state.player.dur=g.state.player.maxDur;g.saveEquipment();const c=give(g,'repairKit');assert.equal(g.act({type:'use',item:'repairKit'}),false);assert.equal(c.qty,1);});
test('lamp oil restores worn equipped torch and headlamp, respects cap and rejects full lights',()=>{const g=arena(),s=g.state;s.expedition.torchDur=5;s.player.inventoryGear.helmet.dur=10;assert(use(g,'lampOil'));assert.equal(s.expedition.torchDur,84);assert.equal(s.player.inventoryGear.helmet.dur,89);s.expedition.torchDur=100;s.player.inventoryGear.helmet.dur=200;assert.equal(g.itemUse('lampOil').ok,false);});
test('bandage heals once per elapsed turn and invalid use retains charge',()=>{const g=arena();g.state.player.hp=1;const t=g.state.turn;assert(use(g,'bandage'));assert.equal(g.state.player.hp,2);assert.equal(g.state.turn,t+1);g.tick(2);assert.equal(g.state.player.hp,Math.min(4,g.state.player.maxHp));assert.equal(g.commonEffects().bandage,0);g.state.player.hp=g.state.player.maxHp;const c=give(g,'bandage');assert.equal(g.act({type:'use',item:'bandage'}),false);assert.equal(c.qty,1);});
test('survey permanently marks nearby terrain without revealing unlit monsters',()=>{const g=arena();g.tile(35,30).seen=false;const m=g.createMonster('skeleton',35,30,900);g.state.monsters=[m];m.freeze=9;assert(use(g,'surveyStone'));assert(g.tile(35,30).seen);assert.equal(g.monsterVisible(m),false);});
test('shock interrupts nearby plans for 2 subsequent turns without damaging terrain',()=>{const g=arena(),s=g.state,m=g.createMonster('skeleton',32,30,901);s.monsters=[m];m.plan={kind:'melee',cells:[{x:32,y:31}],due:s.turn+3};const kind=g.tile(32,30).kind;assert(use(g,'shockBomb',{x:32,y:30}));assert.equal(m.plan,null);assert.equal(m.freeze,2);assert.equal(g.tile(32,30).kind,kind);g.tick(2);assert.equal(m.freeze,0);});
test('hunter adds one effective strike damage but cannot bypass beetle shell',()=>{const g=arena();give(g,'hunterCharm');const m=g.createMonster('sentinel',31,30,902);m.hp=6;m.freeze=9;g.state.monsters=[m];assert(g.strikeMonster(m));assert.equal(m.hp,4);const b=g.createMonster('beetle',31,30,903);b.facing=[-1,0];b.hp=6;g.state.monsters=[b];assert(g.strikeMonster(b));assert.equal(b.hp,6);});
test('wick halves equipped fuel but not placed fuel and persists through saves',()=>{const g=arena();give(g,'wickCharm');g.tile(33,33).torch=true;g.tile(33,33).light={id:'torch',dur:50,max:100};const before=g.lightDurability('torch');g.tick(4);assert.equal(g.lightDurability('torch'),before-2);assert.equal(g.tile(33,33).light.dur,46);const saved=JSON.parse(JSON.stringify(g.exportCampaign())),h=new E(1);assert(h.restoreCampaign(saved));assert(h.cardBuff('wickCharm'));assert.equal(h.commonEffects().haste,0);});
test('full pack keeps random monster drops on the ground; supply duplicates stack normally',()=>{const g=arena();while(g.countSlots()<15)give(g,'bread');let drops=0;for(let id=1000;id<1040;id++){const m=g.createMonster('skeleton',31,30,id);g.state.monsters=[m];g.killMonster(m);drops+=(g.tile(31,30).cards||[]).length;g.tile(31,30).cards=[];}assert(drops>0);assert.equal(g.countSlots(),15);const c=g.makeCard('repairKit',2);g.tile(30,30).cards=[c];assert.equal(g.takeCard(c.uid),false);assert.equal(g.groundCards()[0].qty,2);});


test('wick does not report extinction during a saved fuel turn at one fuel',()=>{const g=arena();give(g,'wickCharm');g.state.turn=2;g.state.expedition.torchDur=1;g.state.player.inventoryGear.helmet.dur=1;const logCount=g.state.logs.length;g.tick();assert.equal(g.state.expedition.torchDur,1);assert.equal(g.state.player.inventoryGear.helmet.dur,1);assert(!g.state.logs.slice(logCount).some(l=>JSON.stringify(l).includes('熄灭')));g.tick();assert.equal(g.state.expedition.torchDur,0);});
