const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const file=process.env.GAME_HTML||path.join(__dirname,'mine5.html');
const ctx=vm.createContext({console});for(const m of fs.readFileSync(file,'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}
const E=ctx.EscapeEngine;
function arena(type='skeleton',kind='melee',distance=1){const g=new E(12345),s=g.state,p=s.player;s.mode='playing';s.monsters=[];s.hazards=[];s.bombs=[];Object.assign(p,{x:40,y:40,hp:6,maxHp:6,armor:0});for(let y=35;y<=45;y++)for(let x=35;x<=45;x++)Object.assign(g.tile(x,y),{kind:'floor',torch:false,gate:null,tidal:false,collapseAt:null,items:{}});const m=g.createMonster(type,40+distance,40,100,[-1,0]);s.monsters=[m];m.alert=10;m.state='windup';m.plan={kind,origin:{x:m.x,y:m.y},cells:[{x:p.x,y:p.y}],due:s.turn+1};s.visionCache=null;return {g,s,p,m};}
for(const [type,kind] of [['undead','melee'],['skeleton','melee'],['bat','melee'],['burrower','melee'],['warden','melee'],['alarm','melee'],['sentinel','sweep'],['beetle','shell']]){
 test(type+' melee respects swift timing and acts only once',()=>{const {g,s,p,m}=arena(type,kind),damage=['undead','sentinel'].includes(type)?2:1;assert.match(g.monsterPlanLabel(m),type==='bat'?/迅捷先手/:/近战打击|横扫|前刺/);assert.equal(g.act({type:'move',dx:0,dy:1}),true);assert.equal(p.hp,type==='bat'?6-damage:6);assert.equal(p.y,41);assert.equal(s.turn,1);assert.equal(m.plan,null);assert.equal(m.actedAt,1);assert.equal(m.x,41);assert.equal(m.y,40);});
 test(type+' killed by player strike cannot retaliate',()=>{const {g,s,p,m}=arena(type,kind);m.hp=1;m.facing=[0,1];assert.equal(g.act({type:'move',dx:1,dy:0}),true);assert.equal(s.monsters.includes(m),false);assert.equal(p.hp,6);assert.equal(s.turn,1);});
 test(type+' surviving player strike retaliates once',()=>{const {g,s,p,m}=arena(type,kind);m.hp=3;m.facing=[0,1];assert.equal(g.act({type:'move',dx:1,dy:0}),true);assert.ok(m.hp>0);assert.equal(p.hp,['undead','sentinel'].includes(type)?4:5);assert.equal(m.actedAt,1);assert.equal(m.plan,null);assert.equal(s.turn,1);});
 test(type+' frozen windup cannot take priority',()=>{const {g,p,m}=arena(type,kind);m.freeze=2;g.act({type:'move',dx:0,dy:1});assert.equal(p.hp,6);assert.equal(m.freeze,1);assert.ok(m.plan);});
}
test('ordinary melee is interrupted by a frost rune before damage',()=>{const {g,p,m}=arena();g.state.player.hands=['pick','rune'];g.state.bag.rune=1;assert.equal(g.act({type:'use',item:'rune'}),true);assert.equal(p.hp,6);assert.ok(m.freeze>0);assert.equal(g.amount('rune'),0);});
test('lethal swift melee prevents item consumption',()=>{const {g,s,p}=arena('bat');p.hp=1;p.hands=['pick','rune'];s.bag.rune=1;g.act({type:'use',item:'rune'});assert.equal(s.mode,'dead');assert.equal(g.amount('rune'),1);assert.equal(s.turn,1);});
test('invalid movement does not consume a melee windup',()=>{const {g,s,p,m}=arena();g.tile(40,41).kind='wall';assert.equal(g.act({type:'move',dx:0,dy:1}),false);assert.equal(s.turn,0);assert.equal(p.hp,6);assert.ok(m.plan);});
for(const [type,kind] of [['eel','spit'],['ghost','dash'],['slime','leap'],['jelly','current'],['warden','gate'],['rat','steal'],['alarm','alarm'],['burrower','burrow']])test(kind+' is not a melee priority action',()=>{const {g,p,m}=arena(type,kind);g.resolvePriority(1);assert.ok(m.plan);assert.equal(p.hp,6);assert.equal(m.actedAt,-1);});
test('two-cell beetle thrust still allows stepping out of its range',()=>{const {g,p}=arena('beetle','shell',2);g.act({type:'move',dx:0,dy:1});assert.equal(p.hp,6);assert.equal(p.y,41);});
test('180 by 180 maps spread connected regions over the larger playable area',()=>{assert.equal(E.GEN.SIZE,180);for(let n=0;n<3;n++){const g=new E(12345);if(n)g.load(n);const s=g.state;assert.equal(s.map.w,180);assert.equal(s.map.h,180);assert.equal(s.map.tiles.length,32400);assert.ok(Math.max(...s.regions.map(r=>r.cx))-Math.min(...s.regions.map(r=>r.cx))>=50);assert.ok(Math.max(...s.regions.map(r=>r.cy))-Math.min(...s.regions.map(r=>r.cy))>=50);assert.ok(s.instabilityAt>600);assert.equal(s.adventure.risk.cells.length,4);s.mode='playing';s.monsters=[];g.tile(s.adventure.risk.neck.x,s.adventure.risk.neck.y).kind='floor';g.tick();assert.equal(s.adventure.risk.due-s.turn,16);s.turn=s.instabilityAt-1;g.tick();assert.ok(s.deadline-s.turn>=340);}});
test('all chapter devices and all exits remain reachable across 60 seeds and tide/gate phases',()=>{for(let seed=1;seed<=60;seed++)for(let n=0;n<3;n++){const g=new E(seed);if(n)g.load(n);const s=g.state;assert.equal(s.layout.problems.length,0,seed+'/'+n+': '+s.layout.problems);assert.ok(s.adventure.risk,'risk branch '+seed+'/'+n);if(n===0)assert.ok(s.map.tiles.some(t=>t.blastSeam),'blast '+seed);if(n===1)assert.equal(s.adventure.gates.length,2,'gates '+seed);if(n===2)assert.ok(s.adventure.tide?.cells.length,'tide '+seed);for(let phase=0;phase<2;phase++){for(const [i,gate] of s.adventure.gates.entries())g.tile(gate.x,gate.y).kind=i===phase?'floor':'hard';if(s.adventure.tide)for(const cell of s.adventure.tide.cells)g.tile(...cell).kind=phase?'water':'floor';const seen=g.reachSet(s.player.x,s.player.y);for(const a of s.sites.filter(a=>a.chapterDevice||['home','miner','mechanical','water','random-exit','workshop','pump','shrine'].includes(a.id)))assert.ok(g.standingNear(seen,a),seed+'/'+n+'/'+phase+'/'+a.id);}}});
