const test=require('node:test'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('C:/Users/Million/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
test('combat cadence keeps budgets, swift priority, recovery, frozen turns and free abilities',async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{let E;Object.defineProperty(window,'EscapeEngine',{get:()=>E,set(T){E=new Proxy(T,{construct(C){const g=Reflect.construct(C,[12345]);window.__testGame=g;return g;}})}})});await page.goto(pathToFileURL(process.env.MINE5_HTML||require('node:path').join(__dirname,'mine5.html')).href);const results=await page.evaluate(()=>{const g=__testGame;g.startExpedition(g.campaign.preparedIds);const s=g.state,p=s.player,results=[];function check(ok,msg){if(!ok)throw Error(msg);results.push(msg);}function arena(){Object.assign(s,{mode:'playing',turn:0,total:0,monsters:[],sites:[],eliteHeat:[],eliteDecoys:[],noises:[],soundCues:[],logs:[],visualEvents:[]});Object.assign(p,{x:30,y:30,hp:50,maxHp:50,armor:0,stun:0,facing:[1,0],equipped:{head:null,body:null,off:null,main:null},inventoryGear:{}});s.expedition.cards=[];s.expedition.torchHand=0;s.environment={version:1,clouds:[],cleared:[],exposure:0};s.params.vision=0;s.params.hazardStart=999999;s.adventure.tide=null;for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',torch:false,light:null,fixedLamp:null,collapseAt:null,gate:false,riskPassage:false,challengeSafe:false,items:{},fog:null});s.lightCache=null;s.visionCache=null;}function add(type,x,y){const m=g.createMonster(type,x,y,999,[-1,0]);m.hp=m.maxHp=50;s.monsters=[m];return m;}function step(){s.turn++;g.monsterTurn();}function wear(id){const c=g.makeCard(id);g.receiveCard(c);p.equipped[EscapeEngine.EQUIPMENT[id].slot]=id;g.syncEquipment();return c.data;}
 arena();let m=add('skeleton',32,30);step();check(m.x===31&&m.plan?.due===2&&p.hp===50,'approach and warn without instant hit');step();check(p.hp===49&&m.plan?.due===3,'attack resolves once and next attack prepares in same phase');step();check(p.hp===48&&m.plan?.due===4,'no alternating idle windup turn');
 arena();m=add('skeleton',31,30);g.planMelee(m);check(m.plan.cells.length===3,'nearby melee fan covers three cells');g.tile(31,31).kind='wall';g.planMelee(m);check(!m.plan.cells.some(c=>c.x===30&&c.y===31),'diagonal fan cannot cut wall corner');g.tile(31,31).kind='floor';g.planMelee(m);g.tile(30,30).kind='wall';const hp=p.hp;g.resolvePlan(m,1);check(p.hp===hp,'new wall blocks previously planned damage');
 arena();m=add('bat',31,30);step();check(m.plan?.due===2&&g.isPriorityMelee(m),'swift prepares without changing priority');g.resolvePriority(2);check(p.hp===49,'swift still strikes before player action');s.turn=2;g.monsterTurn();check(p.hp===49&&m.plan?.due===3,'swift is not hit twice by phase-end prepare');
 arena();m=add('skeleton',31,30);m.freeze=1;step();check(m.freeze===0&&!m.plan&&p.hp===50,'last frozen turn does not create a new plan');step();check(m.plan?.due===3,'thawed enemy may prepare on subsequent action');
 arena();m=add('skeleton',31,30);m.recoverUntil=2;step();check(!m.plan,'recovery still protects first recovery turn');step();check(m.plan?.due===3&&p.hp===50,'last recovery turn ends by preparing without early damage');
 arena();m=add('elite_stoker',34,30);step();check(m.x===33&&m.plan?.kind==='elite_fire'&&m.plan.due===2,'elite moves once and prepares next-action attack');step();check(p.hp===49&&m.plan===null&&m.recoverUntil===4,'elite strikes once then retains recovery');s.eliteHeat=[];step();check(!m.plan,'elite early recovery has no new plan');step();check(m.plan?.due===5&&p.hp===49,'elite final recovery prepares next strike, no immediate hit');
 arena();m=add('elite_mother',32,30);step();step();check(s.monsters.filter(a=>a.eliteSummon).length===1,'phase-end preparation does not duplicate summons');
 arena();m=add('beetle',33,30);step();check(m.x===32&&m.plan?.kind==='shell'&&m.plan.due===2,'special attacker moves into range and prepares');
 arena();m=add('skeleton',31,30);const v=wear('elite_hook');g.planMelee(m);const turn=s.turn,h=p.hp,charges=v.charges;check(g.eliteActive('elite_hook',[1,0]),'free hook succeeds on a warned monster');check(s.turn===turn&&p.hp===h&&!m.plan&&v.charges===charges-1,'free hook interrupts without phase-end retarget or attack');const cloak=wear('elite_cloak');const count=cloak.charges;check(g.eliteActive('elite_cloak',[0,1],{x:30,y:31}),'free cloak chooses one tile');check(s.turn===turn&&!m.plan&&cloak.charges===count-1,'free cloak creates no monster phase');
 arena();m=add('elite_stoker',34,30);g.monsterVisible=()=>false;g.monsterPlanVisible=()=>false;step();check(!s.logs.some(l=>String(l.text).includes('下一次')),'unseen preparation does not publish attack warning');return results;});assert(results.length>=20);assert.deepEqual(errors,[]);console.log(results.join('\n'));}finally{await browser.close();}});
