const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');const html=fs.readFileSync(process.env.GAME_HTML||process.env.MINE5_HTML||path.join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function game(n=0){const g=new E(12345);g.enableCards();g.startExpedition(g.campaign.preparedIds,n,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);g.state.mode='playing';g.state.monsters=[];g.state.bombs=[];g.state.hazards=[];g.state.params.hazardStart=999999;return g;}
function arena(){const g=game(),s=g.state,p=s.player;p.x=30;p.y=30;p.hp=p.maxHp=6;p.armor=0;p.inventoryGear.clothes.armor=0;for(let y=24;y<=38;y++)for(let x=24;x<=38;x++)Object.assign(g.tile(x,y),{kind:'floor',items:{},cards:[],equipment:[],collapseAt:null,tidal:false,gate:null,fog:null});s.lightCache=null;s.visionCache=null;return g;}
function near(g,id){const a=g.state.sites.find(a=>a.id===id);assert(a,id);a.discovered=true;g.state.player.x=a.x;g.state.player.y=a.y;return a;}
function quiet(g){g.tick=function(n=1){this.state.turn+=n;this.state.total+=n;this.challengeTurn();};return g;}
function plan(g,type,kind='melee'){const p=g.state.player,m=g.createMonster(type,p.x+1,p.y,999,[-1,0]);m.hp=8;m.alert=8;m.plan={kind,cells:[{x:p.x,y:p.y}],origin:{x:m.x,y:m.y},due:g.state.turn+1};g.state.monsters=[m];return m;}

test('spiked shield blocks with finite damage against ordinary and elite attackers',()=>{const g=arena();g.receiveCard(g.makeCard('shield'));g.equipGear('off','shield');const d=g.state.player.inventoryGear.shield,before=d.dur,m=g.createMonster('skeleton',31,30,901);g.state.monsters=[m];g.monsterHit(m);assert.equal(g.state.player.hp,6);assert.equal(m.hp,2);assert(g.state.monsters.includes(m));assert.equal(d.dur,before-1);g.monsterHit(m);assert.equal(m.hp,1);g.monsterHit(m);assert(!g.state.monsters.includes(m));const ghost=g.createMonster('ghost',31,30,902);g.state.monsters=[ghost];const dur=d.dur;g.monsterHit(ghost);assert.equal(d.dur,dur);assert.equal(g.state.player.hp,5);});
test('magnetic suit rewards each opened mineral vein once and never vacuums remote drops',()=>{const g=arena();g.receiveCard(g.makeCard('lodestone'));g.equipGear('body','lodestone');for(const [x,y]of [[32,30],[33,30]])Object.assign(g.tile(x,y),{kind:'ore',mineral:'iron',items:{},mineralReleased:false,magnetReleased:false});assert(g.eliteBreak(32,30));const t=g.tile(32,30);assert.equal(t.items.ore,3);assert.equal(g.amount('ore'),0);g.eliteBreak(32,30);assert.equal(t.items.ore,3);g.explode({x:33,y:30});assert.equal(g.tile(33,30).items.ore,3);assert.equal(t.items.ore,3);assert(g.cost('repair')>=1);});
test('every theme gains small permanent lamps on traversable ground',()=>{for(const n of [0,1,2]){const g=game(n),s=g.state,lights=s.map.tiles.filter(t=>t.fixedLamp);assert(lights.length>=s.regions.length);assert(lights.length<65);assert(lights.every(t=>t.fixedLamp.radius===2&&t.kind==='floor'&&!t.tidal&&!t.riskPassage));const before=JSON.stringify(lights.map(t=>t.fixedLamp));g.seedPermanentLights();g.burnLights();g.burnLights();assert.equal(JSON.stringify(lights.map(t=>t.fixedLamp)),before);}});
test('permanent light is small, obeys walls, survives save and does not become collectible fuel',()=>{const g=arena(),s=g.state;g.equipGear('off',null);g.equipGear('head',null);for(const t of s.map.tiles){delete t.fixedLamp;t.torch=false;t.light=null;delete t.fog;}s.environment={version:1,clouds:[],cleared:[],exposure:0};g.tile(35,30).fixedLamp={radius:2};s.visionCache=null;s.lightCache=null;assert.equal(g.lightLevel(35,30),3);assert.equal(g.lightLevel(37,30),2);assert.equal(g.lightLevel(38,30),1);assert.equal(g.lightLevel(39,30),0);g.tile(34,30).kind='wall';s.lightCache=null;s.visionCache=null;assert.equal(g.lightLevel(35,30),0);g.tile(34,30).kind='floor';s.player.x=35;s.visionCache=null;s.lightCache=null;g.receiveCard(g.makeCard('torch'));assert.equal(g.placeableLight('torch'),null);const saved=JSON.parse(JSON.stringify(g.exportCampaign()));const h=new E(17);h.enableCards();assert(h.restoreCampaign(saved));assert.equal(h.tile(35,30).fixedLamp.radius,2);assert.equal(h.tile(35,30).light,null);});
