const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const ctx=vm.createContext({console});for(const m of fs.readFileSync(path.join(__dirname,'mine5.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}
const E=ctx.EscapeEngine;const game=n=>{const g=new E(12345);if(n)g.load(n);g.state.mode='playing';g.state.monsters=[];return g;};
for(let n=0;n<3;n++){const g=game(n),s=g.state;assert.equal(s.layout.mapStyle,['rail-mine','ring-city','braided-river'][n]);assert.ok(s.challenge);for(const id of ['mechanical']){const exit=s.sites.find(a=>a.id===id);s.player.x=exit.x;s.player.y=exit.y;s.routeChoice=id;s.local.part=true;assert.equal(g.act({type:'choose',kind:'depart'}),false,'a found part must not bypass chapter '+n);assert.equal(g.act({type:'choose',kind:'force'}),false,'mining must not bypass chapter '+n);assert.equal(s.level,n);assert.equal(s.turn,0);}assert.equal(s.layout.problems.length,0,s.layout.problems.join(','));}
console.log('Distinct map styles and mandatory chapter exits passed.');
function approach(g,id){const a=g.state.sites.find(v=>v.id===id);assert.ok(a,id);a.discovered=true;g.state.player.x=a.x;g.state.player.y=a.y;return a;}
const mine=game(0),mc=mine.state.challenge;mine.state.local.part=true;mine.setAmount('ore',3);approach(mine,'cart-control');assert.equal(mine.act({type:'choose',kind:'chapter:cart:repair-ore'}),true);for(const repair of mc.trackRepairs){approach(mine,repair.siteId);assert.equal(mine.act({type:'choose',kind:'chapter:track:'+repair.siteId}),true);}approach(mine,'cart-control');assert.equal(mine.act({type:'choose',kind:'chapter:start'}),true);mine.state.player.x=mc.cart.x;mine.state.player.y=mc.cart.y;const enemy=mine.createMonster('undead',mc.path[mc.index+1].x,mc.path[mc.index+1].y,987);mine.state.monsters=[enemy];let before=mc.index;mine.challengeTurn();assert.equal(mc.index,before,'cart stops for threats');enemy.freeze=4;mine.challengeTurn();assert.equal(mc.index,before+1,'freezing opens an escort window');mine.state.monsters=[];mine.state.player.x=0;mine.state.player.y=0;before=mc.index;mine.challengeTurn();assert.equal(mc.index,before,'cannot start and abandon cart');let guard=0;while(!mc.complete&&guard++<mc.path.length+20){mine.state.player.x=mc.cart.x;mine.state.player.y=mc.cart.y;mine.act({type:'wait'});}assert.equal(mc.complete,true);approach(mine,'mechanical');mine.state.routeChoice='mechanical';mine.state.local.part=false;assert.equal(mine.act({type:'choose',kind:'depart'}),true);assert.equal(mine.state.level,1);
const city=game(1),cc=city.state.challenge;approach(city,'rune-'+cc.order[0]);assert.equal(city.act({type:'choose',kind:'chapter:rune:'+cc.order[0]}),false);approach(city,'city-inscription');assert.equal(city.act({type:'choose',kind:'chapter:read'}),true);assert.equal(city.state.turn,0);approach(city,'rune-'+cc.order[1]);city.act({type:'choose',kind:'chapter:rune:'+cc.order[1]});assert.equal(cc.progress,0);for(const id of cc.order){approach(city,'rune-'+id);assert.equal(city.act({type:'choose',kind:'chapter:rune:'+id}),true);}assert.equal(cc.complete,true);approach(city,'water');city.state.routeChoice='water';assert.equal(city.act({type:'choose',kind:'depart'}),true);assert.equal(city.state.level,2);
const river=game(2),rc=river.state.challenge;approach(river,'sluice-high');assert.equal(river.act({type:'choose',kind:'chapter:sluice:high'}),false);assert.equal(river.state.turn,0);river.setAmount('ore',6);for(const key of ['a','b']){approach(river,'river-anchor-'+key);assert.equal(river.act({type:'choose',kind:'chapter:anchor:'+key+':ore'}),true);}approach(river,'sluice-high');river.state.turn=8;river.adventureTurn();assert.equal(river.act({type:'choose',kind:'chapter:sluice:high'}),true);approach(river,'sluice-low');assert.equal(river.act({type:'choose',kind:'chapter:sluice:low'}),false);river.state.turn=16;river.adventureTurn();assert.equal(river.act({type:'choose',kind:'chapter:sluice:low'}),true);assert.equal(rc.complete,true);approach(river,'mechanical');river.state.routeChoice='mechanical';river.state.turn=24;river.adventureTurn();assert.equal(river.act({type:'choose',kind:'depart'}),false);river.state.turn=32;river.adventureTurn();assert.equal(river.act({type:'choose',kind:'depart'}),true);assert.equal(river.state.mode,'home');assert.equal(river.state.level,0);assert.equal(river.state.depth,2);
for(let n=0;n<3;n++){const variants=new Set();for(let seed=1;seed<50&&variants.size<3;seed++){const v=E.GEN.rng(E.GEN.stream(seed,'chapter-blueprint',n)).int(3);if(variants.has(v))continue;variants.add(v);const g=new E(seed);if(n)g.load(n);const s=g.state;assert.ok(s.adventure.risk,'missing optional reward '+n+'/'+v);assert.equal(s.layout.problems.length,0,'layout '+n+'/'+v+': '+s.layout.problems.join(','));let seen=g.reachSet(s.player.x,s.player.y);for(const a of s.sites.filter(a=>a.chapterDevice))assert.ok(g.standingNear(seen,a),'unreachable device '+a.id+' '+n+'/'+v);if(n===0)assert.ok(s.challenge.path.length>8);if(n===2){s.mode='playing';s.turn=8;g.adventureTurn();seen=g.reachSet(s.player.x,s.player.y);for(const a of s.sites.filter(a=>a.chapterDevice||a.id==='mechanical'||a.id==='water'))assert.ok(g.standingNear(seen,a),'high tide disconnects '+a.id+' variant '+v);}}assert.equal(variants.size,3);}
console.log('Chapter checks passed: escort threats/range, sequence order, tide windows, completed exits and all nine layout variants.');

const blocked=game(1);blocked.state.challenge.complete=true;approach(blocked,'water');blocked.state.routeChoice='water';blocked.state.player.armor=0;const attacker=blocked.createMonster('undead',blocked.state.player.x+1,blocked.state.player.y,667,[-1,0]);blocked.state.monsters=[attacker];blocked.planMelee(attacker);blocked.state.bombs=[{x:blocked.state.player.x+10,y:blocked.state.player.y,due:3}];const hp=blocked.state.player.hp;assert.equal(blocked.act({type:'choose',kind:'depart'}),false);assert.equal(blocked.state.turn,0);assert.equal(blocked.state.player.hp,hp);blocked.state.bombs=[];blocked.state.companion={x:1,y:1,name:'远处同伴'};assert.equal(blocked.act({type:'choose',kind:'depart'}),false);assert.equal(blocked.state.turn,0);assert.equal(blocked.state.player.hp,hp);console.log('Blocked evacuation preserves time and prevents priority damage.');
