const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');let browser;test.before(async()=>{browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});});test.after(async()=>browser?.close());
async function pageFor(t,viewport={width:1280,height:900}){const p=await browser.newPage({viewport,reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await p.close();assert.deepEqual(errors,[]);});await p.addInitScript(()=>{let Engine;Object.defineProperty(window,'EscapeEngine',{get(){return Engine;},set(E){Engine=new Proxy(E,{construct(T,args){const g=Reflect.construct(T,[12345]);window.__testGame=g;return g;}});}});});await p.goto(pathToFileURL(process.env.MINE5_HTML||path.join(__dirname,'mine5.html')).href);p.setDefaultTimeout(5000);return p;}
async function ensureDock(p){await p.keyboard.press('Escape');if(!await p.locator('#card-dock').isVisible())await p.locator('#card-tab').click();}
async function pinDock(p){if(await p.locator('[data-card-pin]').getAttribute('aria-pressed')!=='true')await p.locator('[data-card-pin]').click();}
async function chest(p){await ensureDock(p);await p.locator('[data-open-chest]').click();}
async function pack(p,n=5){await p.evaluate(()=>{const g=__testGame,ids=['kit','bread','bomb','rope','quiet'];g.campaign.preparedIds=[];for(const id of ids)if(!g.campaign.stock.some(c=>c.id===id))g.campaign.stock.push(g.makeCard(id));const chosen=ids.map(id=>g.campaign.stock.find(c=>c.id===id));g.campaign.stock=[...chosen,...g.campaign.stock.filter(c=>!chosen.includes(c))];});await chest(p);for(let i=0;i<n;i++)await p.locator('[data-pack-card][title="带入卡包"]').first().click();await p.keyboard.press('Escape');}
async function enter(p){await p.locator('#task-button').click();await p.locator('[data-expedition-start]').click();}
async function depart(p){await pack(p);await enter(p);await p.evaluate(()=>{__testGame.state.monsters=[];});await ensureDock(p);await p.locator('[data-card-select]').filter({hasText:'基础矿工套装'}).click();await p.locator('[data-kit-open]').click();await p.keyboard.press('Escape');}

test('camp is playable without a forced dialog; physical chest transfers at most five cards',async t=>{const p=await pageFor(t);assert.equal(await p.locator('#dialog').evaluate(e=>e.open),false);assert.equal(await p.locator('#quickbar').count(),0);assert.equal(await p.locator('[data-quick]').count(),0);
 // Walk to the chest, then use the normal world interaction.
 await p.locator('#world').focus();await p.keyboard.press('ArrowLeft');await p.keyboard.press('ArrowDown');await p.keyboard.press('Space');assert.equal(await p.locator('#dialog').getAttribute('data-kind'),'loadout');
 for(let i=0;i<3;i++)await p.locator('[data-pack-card][title="带入卡包"]').first().click();await p.locator('[data-pack-card][title="带入卡包"]').first().click();assert.equal(await p.evaluate(()=>__testGame.campaign.preparedIds.length),5);assert.match(await p.locator('#dialog').innerText(),/5\/5/);
 await p.locator('[data-pack-card][title="存入箱子"]').first().click();assert.equal(await p.evaluate(()=>__testGame.campaign.preparedIds.length),4);assert.equal(await p.evaluate(()=>__testGame.campaign.stock.length),10);await p.keyboard.press('Escape');await p.reload();assert.equal(await p.evaluate(()=>__testGame.campaign.preparedIds.length),4);assert.equal(await p.locator('#dialog').evaluate(e=>e.open),false);
});
test('zero or one card can depart; desktop keeps the side hand pinned open',async t=>{for(const n of [0,1]){const p=await pageFor(t);await pack(p,n);await enter(p);assert.equal(await p.evaluate(()=>__testGame.state.mode),'playing');assert.equal(await p.evaluate(()=>__testGame.countSlots()),n);assert.equal(await p.locator('#card-tab').isVisible(),true);assert.equal(await p.locator('#card-dock').isVisible(),true);assert.equal(await p.locator('#card-dock').getAttribute('data-position'),'side');assert.equal(await p.locator('[data-card-pin]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#dialog').evaluate(e=>e.open),false);}});
test('selected card uses one charge and can be dropped without losing remaining quantity',async t=>{const p=await pageFor(t);await depart(p);await p.evaluate(()=>{__testGame.state.player.hp=1;});await ensureDock(p);await p.locator('[data-card-select]').filter({hasText:'面包'}).click();await p.locator('[data-card-use]').click();await ensureDock(p);await p.locator('[data-card-select]').filter({hasText:'面包'}).click();assert.match(await p.locator('[data-card-select]').filter({hasText:'面包'}).innerText(),/2\/3/);await p.locator('[data-card-drop]').click();assert.equal(await p.evaluate(()=>__testGame.groundCards()[0].qty),2);});
test('pinned hand stays floating while using a card and does not advance time when inspected',async t=>{const p=await pageFor(t);await depart(p);await ensureDock(p);await pinDock(p);await p.evaluate(()=>{__testGame.state.player.hp=1;});const before=await p.evaluate(()=>__testGame.state.total);await p.locator('[data-card-select]').filter({hasText:'面包'}).hover();assert.equal(await p.locator('#card-popover').isVisible(),true);assert.equal(await p.evaluate(()=>__testGame.state.total),before);await p.locator('[data-card-select]').filter({hasText:'面包'}).click();await p.locator('[data-card-use]').click();assert.equal(await p.locator('#card-dock').isVisible(),true);assert.equal(await p.locator('#card-tab').isVisible(),true);assert.equal(await p.evaluate(()=>__testGame.state.total),before+1);});
test('card keyboard focus does not move the player; Space selects a card',async t=>{const p=await pageFor(t);await depart(p);await ensureDock(p);const card=p.locator('[data-card-select]').filter({hasText:'面包'});await card.focus();const before=await p.evaluate(()=>__testGame.state.total);await p.keyboard.press('ArrowDown');await p.keyboard.press('Space');assert.equal(await p.locator('#card-popover').isVisible(),true);assert.equal(await p.evaluate(()=>__testGame.state.total),before);});
test('extraction returns cards to chest and workbench repairs the same damaged equipment',async t=>{const p=await pageFor(t);await depart(p);await p.evaluate(()=>{const g=__testGame;g.state.player.dur=41;g.state.ore=7;g.settleExpedition(true);});await p.keyboard.press('z');await p.locator('[data-return-camp]').click();assert.equal(await p.locator('#dialog').evaluate(e=>e.open),false);await chest(p);await p.locator('#chest-search').fill('普通镐');assert.match(await p.locator('[data-pack-card]').filter({hasText:'普通镐'}).innerText(),/41\/220/);await p.locator('#chest-search').fill('');await p.keyboard.press('Escape');await p.evaluate(()=>{__testGame.state.home={x:2,y:0,rested:false};});await p.locator('#world').focus();await p.keyboard.press('Space');await p.locator('[data-stock-repair]').filter({hasText:'修复 70'}).click();assert.equal(await p.evaluate(()=>__testGame.campaign.stock.find(c=>c.id==='normal').data.dur),111);await p.keyboard.press('Escape');await pack(p,1);await enter(p);assert.equal(await p.evaluate(()=>__testGame.state.expedition.phase),'active');});
test('reload preserves expedition cards and original camp stock',async t=>{const p=await pageFor(t);await depart(p);await p.evaluate(()=>window.dispatchEvent(new Event('pagehide')));const before=await p.evaluate(()=>({stock:__testGame.campaign.stock.length,cards:__testGame.countSlots(),region:__testGame.state.level}));await p.reload();assert.deepEqual(await p.evaluate(()=>({stock:__testGame.campaign.stock.length,cards:__testGame.countSlots(),region:__testGame.state.level})),before);});
for(const viewport of [{width:390,height:844},{width:844,height:390}])test('chest, pack, floating card and equipment fit '+viewport.width+'x'+viewport.height,async t=>{const p=await pageFor(t,viewport);await depart(p);await ensureDock(p);await p.locator('[data-card-select]').filter({hasText:'面包'}).click();for(const sel of ['#card-dock','#card-popover']){const r=await p.locator(sel).boundingBox();assert.ok(r.x>=0&&r.x+r.width<=viewport.width&&r.y+r.height<=viewport.height);}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.keyboard.press('Escape');await p.locator('#equipment-button').click();const r=await p.locator('.character-sheet').boundingBox();assert.ok(r.x>=0&&r.x+r.width<=viewport.width);assert.equal(await p.locator('[data-equipment-slot]').count(),4);assert.equal(await p.locator('.character-portrait svg').count(),1);});
test('native departure inputs do not activate actions or move focus to other controls',async t=>{const p=await pageFor(t);await p.locator('#task-button').click();const select=p.locator('#expedition-region');await select.focus();await p.keyboard.press('ArrowDown');assert.equal(await select.evaluate(e=>document.activeElement===e),true);await p.locator('#departure-ore').fill('0');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>__testGame.state.expedition.phase),'prepare');});
test('equipment sheet returns a worn pick to its card and equips it again',async t=>{const p=await pageFor(t);await depart(p);await p.evaluate(()=>{__testGame.state.player.dur=27;});await p.locator('#equipment-button').click();await p.locator('[data-equipment-slot="main"]').click();await p.locator('[data-unwear="main"]').click();assert.equal(await p.evaluate(()=>__testGame.state.player.equipped.main),null);await ensureDock(p);const card=p.locator('[data-card-select]').filter({hasText:'普通镐'});await card.click();assert.match(await card.innerText(),/27\/220/);await p.locator('[data-wear="normal"]').click();assert.equal(await p.evaluate(()=>__testGame.state.player.equipped.main),'normal');assert.equal(await p.evaluate(()=>__testGame.state.player.dur),27);});

test('hover preview remains usable across the gap between pack and floating card',async t=>{const p=await pageFor(t);await depart(p);await ensureDock(p);await p.evaluate(()=>{__testGame.state.player.hp=1;});await p.locator('[data-card-select]').filter({hasText:'面包'}).hover();const r=await p.locator('#card-popover [data-card-use]').boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2,{steps:30});assert.equal(await p.locator('#card-popover').isVisible(),true);await p.mouse.click(r.x+r.width/2,r.y+r.height/2);assert.equal(await p.evaluate(()=>__testGame.state.expedition.cards.find(c=>c.id==='bread').qty),2);});

test('failed browser storage shows an error without adding routine save microcopy',async t=>{const p=await pageFor(t);assert.equal(await p.locator('#save-notice').isVisible(),false);await p.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Quota exceeded','QuotaExceededError');};});await pack(p,1);assert.equal(await p.locator('#save-notice').isVisible(),true);assert.match(await p.locator('#save-notice').innerText(),/无法保存/);});

test('floating hand never changes map or action geometry while toggling or pinning',async t=>{const p=await pageFor(t);const rects=()=>p.evaluate(()=>['#world','.player-panel','#task-button'].map(sel=>{const r=document.querySelector(sel).getBoundingClientRect();return [r.x,r.y,r.width,r.height];}));const before=await rects();await ensureDock(p);await pinDock(p);assert.deepEqual(await rects(),before);assert.equal(await p.locator('#card-tab').isVisible(),true);await p.locator('#card-tab').click();assert.equal(await p.locator('#card-dock').isVisible(),false);assert.deepEqual(await rects(),before);await ensureDock(p);assert.deepEqual(await rects(),before);});

for(const viewport of [{width:1280,height:900},{width:390,height:844},{width:844,height:390}])test('full fifteen-card hand packs without scrollbars and every card stays selectable at '+viewport.width,async t=>{const p=await pageFor(t,viewport);await depart(p);await p.evaluate(()=>{const g=__testGame;while(g.countSlots()<15)g.receiveCard(g.makeCard('rune'));});const before=await p.locator('#world').boundingBox();await ensureDock(p);assert.equal(await p.locator('.hand-row [data-card-select]').count(),15);assert.deepEqual(await p.locator('#world').boundingBox(),before);assert.equal(await p.locator('#card-dock .hand-scroll').count(),0);const uids=await p.locator('.hand-row [data-card-select]').evaluateAll(cards=>cards.map(c=>c.dataset.cardSelect));for(const uid of uids){const point=await p.evaluate(uid=>{const card=document.querySelector('[data-card-select="'+uid+'"]'),r=card.getBoundingClientRect();for(let y=Math.max(1,r.y+4);y<Math.min(innerHeight,r.bottom-2);y+=5)for(let x=Math.max(1,r.x+4);x<Math.min(innerWidth,r.right-2);x+=4)if(document.elementFromPoint(x,y)?.closest('[data-card-select]')===card)return{x,y};return null;},uid);assert.ok(point,'each card has an exposed clickable area');await p.mouse.click(point.x,point.y);assert.equal(await p.locator('[data-card-select="'+uid+'"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#card-popover').isVisible(),true);await p.locator('[data-card-dismiss]').click();}const limits=await p.locator('.hand-spread').evaluate(el=>({width:el.clientWidth,content:el.scrollWidth,overflow:getComputedStyle(el).overflowX}));assert.ok(limits.content<=limits.width+1);assert.ok(!['auto','scroll'].includes(limits.overflow));const last=p.locator('.hand-row [data-card-select]').last();await last.focus();await p.keyboard.press('Space');assert.match(await p.locator('#card-popover').innerText(),/寒霜符石/);await p.locator('[data-card-dismiss]').click();await p.locator('[data-card-close]').click();assert.deepEqual(await p.locator('#world').boundingBox(),before);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);});

test('camp new-start entry preserves progress on cancel and rolls a fresh stocked camp only on confirm',async t=>{const p=await pageFor(t);await p.evaluate(()=>{__testGame.campaign.ore=19;});const before=await p.evaluate(()=>JSON.stringify(__testGame.campaign));await p.locator('#more-button').click();await p.locator('#restart-button').click();await p.locator('#dialog [data-action="close"]').click();assert.equal(await p.evaluate(()=>JSON.stringify(__testGame.campaign)),before);await p.locator('#more-button').click();await p.locator('#restart-button').click();await p.locator('[data-new-campaign]').click();assert.deepEqual(await p.evaluate(()=>__testGame.campaign.preparedIds.map(uid=>__testGame.campaign.stock.find(c=>c.uid===uid).id)),['bread','kit']);assert.equal(await p.evaluate(()=>__testGame.campaign.stock.length),10);assert.equal(await p.evaluate(()=>__testGame.campaign.ore),4);});

test('normal motion in camp does not accumulate or replay earlier steps',async t=>{const p=await pageFor(t);await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#world').focus();await p.keyboard.press('ArrowLeft');await p.waitForTimeout(170);await p.keyboard.press('ArrowDown');assert.equal(await p.evaluate(()=>__testGame.state.visualEvents.length),1);await p.waitForTimeout(170);await p.keyboard.press('Space');await p.waitForFunction(()=>document.querySelector('#dialog').open);assert.equal(await p.locator('#dialog').getAttribute('data-kind'),'loadout');assert.equal(await p.evaluate(()=>__testGame.state.visualEvents.length),0);});
