const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const html=fs.readFileSync(process.env.MINE5_HTML||'D:/MY_Blog/source/game/魏晋事业/mine5.html','utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function arena(){const g=new E(12345);g.enableCards();g.startExpedition(g.campaign.preparedIds,0,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.params.vision=0;s.player.x=30;s.player.y=30;s.player.facing=[1,0];s.environment={version:1,clouds:[],cleared:[],exposure:0};for(const t of s.map.tiles){delete t.fog;delete t.fixedLamp;t.torch=false;t.light=null;}for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',collapseAt:null});g.equipGear('head',null);s.visionCache=null;s.lightCache=null;return g;}
test('natural fog pockets exist away from camp and interaction sites',()=>{const g=new E(17);assert.ok(g.state.map.tiles.some(t=>t.fog));const home=g.state.sites.find(a=>a.id==='home');for(let y=0;y<g.state.map.h;y++)for(let x=0;x<g.state.map.w;x++)if(g.tile(x,y).fog){assert.ok(Math.abs(x-home.x)+Math.abs(y-home.y)>10);assert.ok(!g.state.sites.some(a=>Math.abs(x-a.x)+Math.abs(y-a.y)<=2));}});
test('smoke dims nearby light, hides distant creatures and blocks enemy sight symmetrically',()=>{const g=arena();assert.equal(g.lightLevel(33,30),3);g.addFog(32,30,2,5,'smoke');assert.equal(g.lightLevel(31,30),2);assert.ok(g.lightLevel(33,30)<=1);const m=g.createMonster('bat',33,30,999);assert.equal(g.monsterVisible(m),false);assert.equal(g.sense(m),false);assert.ok(g.lightLevel(30,30)>=2);});
test('clear zones immediately restore light and expire with actions',()=>{const g=arena();g.addFog(32,30,2,20,'smoke');g.clearFog(32,30,4,2);assert.equal(g.fogAt(32,30),0);assert.equal(g.lightLevel(33,30),3);g.tick(2);assert.ok(g.fogAt(32,30)>0);assert.ok(g.lightLevel(33,30)<=1);});
test('smoke expiry invalidates visibility and a wall still blocks cleared fog',()=>{const g=arena();g.addFog(32,30,2,2);g.tick(2);assert.equal(g.fogAt(32,30),0);assert.equal(g.lightLevel(33,30),3);g.tile(31,30).kind='wall';g.state.visionCache=null;assert.equal(g.lightLevel(33,30),0);});
test('spore exposure hurts after three actions and resets after leaving',()=>{const g=arena(),hp=g.state.player.hp;g.addFog(30,30,1,10,'spores');g.tick(2);assert.equal(g.state.player.hp,hp);g.tick();assert.equal(g.state.player.hp,hp-1);g.state.player.x=34;g.tick();assert.equal(g.state.environment.exposure,0);});
test('environment survives serialization and old saves initialize safely',()=>{const g=arena();g.addFog(32,30,2,8);g.tick();const save=JSON.parse(JSON.stringify(E.encodeSave(g.exportCampaign()))),h=new E(1);h.enableCards();assert.ok(h.restoreCampaign(E.decodeSave(save)));assert.ok(h.fogAt(32,30)>0);assert.equal(h.state.environment.clouds[0].until,h.state.turn+7);delete save.state.environment;const k=new E(2);k.enableCards();assert.ok(k.restoreCampaign(E.decodeSave(save)));assert.equal(k.state.environment.version,1);});
test('new floors reset transient clouds and exposure and seed their own terrain',()=>{const g=arena();g.addFog(30,30,2,99,'spores');g.clearFog(35,30,1,50);g.state.environment.exposure=2;g.load(1);assert.equal(g.state.environment.clouds.length,0);assert.equal(g.state.environment.cleared.length,0);assert.equal(g.state.environment.exposure,0);assert.ok(g.state.map.tiles.some(t=>t.fog==='spores'));});
test('fog never passes a wall; dispersal cannot clear the other side',()=>{const g=arena();g.tile(31,30).kind='wall';g.tile(32,30).fog='spores';g.addFog(30,30,3,10,'smoke');assert.equal(g.fogKind(32,30),'spores');g.clearFog(30,30,3,5);assert.equal(g.fogKind(30,30),null);assert.equal(g.fogKind(32,30),'spores');});
