const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/Million/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
async function scene(t){const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),p=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));t.after(async()=>{await browser.close();assert.deepEqual(errors,[]);});await p.addInitScript(()=>{let Engine;Object.defineProperty(window,'EscapeEngine',{get(){return Engine;},set(E){Engine=new Proxy(E,{construct(T,args){const g=Reflect.construct(T,[12345]);window.__testGame=g;return g;}});}});window.__capture=false;window.__marks=[];for(const key of ['fillRect','strokeRect','fillText']){const original=CanvasRenderingContext2D.prototype[key];CanvasRenderingContext2D.prototype[key]=function(...args){if(window.__capture&&this.canvas.id==='world')window.__marks.push({key,args,fill:this.fillStyle,stroke:this.strokeStyle});return original.apply(this,args);};}});await p.goto(pathToFileURL(process.env.GAME_HTML||process.env.MINE5_HTML||'D:/MY_Blog/source/game/魏晋事业/mine5.html').href);await p.evaluate(()=>{const g=__testGame;g.startExpedition(g.campaign.preparedIds);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.bombs=[];s.hazards=[];s.player.x=30;s.player.y=30;s.player.hp=s.player.maxHp=20;s.player.armor=0;s.player.facing=[1,0];s.player.equipped={main:null,body:null,head:null,off:null};s.player.inventoryGear={};s.expedition.cards=[];s.expedition.torchHand=0;s.params.vision=0;s.params.hazardStart=999999;s.logs=[];s.visualEvents=[];s.environment.clouds=[];s.environment.cleared=[];s.adventure.ice=[];s.adventure.tide=null;s.adventure.risk=null;for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',fog:null,torch:false,light:null,fixedLamp:null,collapseAt:null,tidal:false,gate:false,riskPassage:false});s.lightCache=null;s.visionCache=null;if(document.querySelector('#dialog').open)document.querySelector('#dialog').close();});await p.keyboard.press('z');await p.keyboard.press('z');return p;}
async function capture(p){return p.evaluate(async()=>{window.__marks=[];window.__capture=true;await new Promise(done=>requestAnimationFrame(()=>requestAnimationFrame(done)));window.__capture=false;return window.__marks;});}
function boxes(marks){return marks.filter(m=>m.key==='strokeRect'&&m.args[2]===68&&m.args[3]===68);}
test('natural skeleton approach immediately warns three forward cells; sidestep is hit and retreat escapes',async t=>{
 const p=await scene(t);
 async function arrange(){await p.evaluate(()=>{const g=__testGame,s=g.state;s.player.x=30;s.player.y=30;s.player.hp=20;s.player.armor=0;s.player.stun=0;s.player.facing=[1,0];s.visualEvents=[];s.effect=null;s.logs=[];const m=g.createMonster('skeleton',32,30,901,[-1,0]);m.hp=m.maxHp=50;s.monsters=[m];s.lightCache=null;s.visionCache=null;});await p.locator('#world').focus();await p.keyboard.press('z');await p.keyboard.press('z');}
 async function advance(key){const turn=await p.evaluate(()=>__testGame.state.turn);await p.locator('#world').focus();await p.keyboard.press(key);await p.waitForFunction(turn=>__testGame.state.turn===turn+1,turn);await p.evaluate(()=>new Promise(r=>setTimeout(r,350)));}
 for(const [key,expected,hp]of [['ArrowDown',{x:30,y:31},19],['ArrowLeft',{x:29,y:30},20]]){
  await arrange();assert.equal(await p.evaluate(()=>!!__testGame.state.monsters[0].plan),false);await advance('.');
  const warning=await p.evaluate(()=>{const s=__testGame.state,m=s.monsters[0];return{x:m.x,y:m.y,turn:s.turn,plan:m.plan,priority:__testGame.isPriorityMelee(m),hp:s.player.hp};});
  assert.deepEqual({x:warning.x,y:warning.y},{x:31,y:30});assert.equal(warning.plan?.kind,'melee','approaching monster must prepare in the same enemy phase');assert.equal(warning.plan.due,warning.turn+1);assert.equal(warning.priority,false);assert.equal(warning.hp,20,'approach only warns; it does not hit immediately');
  assert.deepEqual(warning.plan.cells.map(c=>[c.x,c.y]).sort(),[[30,29],[30,30],[30,31]]);
  const marks=boxes(await capture(p)),unique=[...new Set(marks.map(m=>m.args.slice(0,4).join(',')))];assert.equal(unique.length,3,'canvas must draw all three warned cells');assert.equal(await p.locator('#danger-banner').isVisible(),true);
  await advance(key);assert.deepEqual(await p.evaluate(()=>({x:__testGame.state.player.x,y:__testGame.state.player.y})),expected);assert.equal(await p.evaluate(()=>__testGame.state.player.hp),hp,key==='ArrowDown'?'sideways move remains inside fan and must take damage':'backward move exits fan before ordinary attack');
 }
});

