const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const html=fs.readFileSync(process.env.MINE5_HTML||require('node:path').join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function arena(){const g=new E(12345);g.enableCards();g.startExpedition(g.campaign.preparedIds,0,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.player.x=30;s.player.y=30;s.player.facing=[1,0];s.player.hp=6;s.player.armor=0;s.eliteHeat=[];s.eliteDecoys=[];s.environment={version:1,clouds:[],cleared:[],exposure:0};for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',collapseAt:null,gate:false,riskPassage:false,challengeSafe:false,items:{},fog:null});s.visionCache=null;s.lightCache=null;return g;}
function add(g,type,x=33,y=30){const m=g.createMonster(type,x,y,999);m.elite=!!E.ELITES[type];g.state.monsters.push(m);return m;}
function wear(g,id){const c=g.makeCard(id);assert.ok(g.receiveCard(c));g.state.player.equipped[E.EQUIPMENT[id].slot]=id;g.syncEquipment();return c.data;}
const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
test('each theme has exactly two reachable elites away from sites across seeds',()=>{for(const seed of [17,55,678]){const g=new E(seed);for(let n=0;n<3;n++){g.load(n);const s=g.state,elites=s.monsters.filter(m=>g.isElite(m)),reachable=g.reachSet(s.layout.start.x,s.layout.start.y);assert.equal(elites.length,2);assert.equal(new Set(elites.map(m=>m.type)).size,2);for(const m of elites){assert.equal(E.ELITES[m.type].level,n);assert.ok(m.elite);assert.ok(reachable.has(m.x+','+m.y));assert.ok(dist(m,s.layout.start)>=20);assert.ok(s.sites.every(a=>dist(a,m)>=5));}}}});
test('elite gear never appears in random starter equipment',()=>{for(let i=0;i<8;i++){const g=new E(i);g.enableCards();assert.ok(g.campaign.stock.every(c=>!c.id.startsWith('elite_')));}});
test('all elites telegraph dodgeable skill for two turns',()=>{for(const type of Object.keys(E.ELITES)){const g=arena(),m=add(g,type);g.sense=()=>true;g.dungeonTurn(m);assert.ok(m.plan);assert.equal(m.plan.due,g.state.turn+1);assert.equal(g.isPriorityMelee(m),false);const plan=m.plan,hp=g.state.player.hp;g.state.player.x=20;g.state.player.y=20;g.resolveDungeonPlan(m,plan,g.state.turn+2);assert.equal(g.state.player.hp,hp);}});
test('ordinary melee no longer receives automatic priority',()=>{const g=arena(),m=add(g,'undead',31,30);g.planMelee(m);assert.equal(g.isPriorityMelee(m),false);});
test('spike shield blocks elites and reflects one without instant kill',()=>{const g=arena(),m=add(g,'elite_bell'),v=wear(g,'shield');const hp=g.state.player.hp;g.monsterHit(m);assert.equal(g.state.player.hp,hp);assert.equal(m.hp,7);assert.equal(v.dur,5);assert.ok(g.state.monsters.includes(m));});
test('bomb deals three to elite but retains ordinary monster blast kills',()=>{const g=arena(),m=add(g,'elite_overseer',35,30),normal=add(g,'rat',35,31);g.explode({x:35,y:30});assert.equal(m.hp,4);assert.ok(g.state.monsters.includes(m));assert.ok(!g.state.monsters.includes(normal));});
test('charge opens ordinary rocks but never task walls and becomes vulnerable',()=>{const g=arena(),m=add(g,'elite_overseer',32,30);m.facing=[1,0];g.tile(33,30).kind='rock';g.tile(34,30).kind='hard';g.tile(34,30).gate=true;const cells=g.eliteCells(m,'elite_charge');assert.ok(cells.some(c=>c.x===33));assert.ok(!cells.some(c=>c.x===34));g.resolveDungeonPlan(m,{kind:'elite_charge',cells,direction:[1,0]},0);assert.equal(g.tile(33,30).kind,'floor');assert.equal(g.tile(34,30).kind,'hard');assert.equal(m.exposedUntil,2);});
test('stoker leaves visible delayed hot ground and exhaust recovery',()=>{const g=arena(),m=add(g,'elite_stoker');g.resolveDungeonPlan(m,{kind:'elite_fire',cells:[{x:30,y:30}],direction:[-1,0]},0);assert.equal(g.state.player.hp,5);assert.equal(g.state.eliteHeat[0].from,1);assert.equal(m.recoverUntil,2);g.state.monsters=[];g.state.turn=1;g.monsterTurn();assert.equal(g.state.player.hp,4);});
test('ferryman hook pulls then sweep uses a new windup; a miss pauses',()=>{const g=arena(),m=add(g,'elite_ferryman',34,30);g.resolveDungeonPlan(m,{kind:'elite_hookshot',cells:[{x:30,y:30}],direction:[-1,0]},0);assert.equal(g.state.player.x,33);assert.equal(g.state.player.hp,6);assert.equal(m.combo,true);g.state.turn=1;g.sense=()=>true;g.dungeonTurn(m);assert.equal(m.plan.kind,'elite_sweep');assert.equal(m.plan.due,2);const h=arena(),n=add(h,'elite_ferryman');h.resolveDungeonPlan(n,{kind:'elite_hookshot',cells:[],direction:[-1,0]},0);assert.equal(n.recoverUntil,2);});
test('mother summons no more than two jellyfish',()=>{const g=arena(),m=add(g,'elite_mother',34,30);for(let n=0;n<6;n++)g.resolveDungeonPlan(m,{kind:'elite_tidewave',cells:[],direction:[-1,0]},n);assert.equal(g.state.monsters.filter(m=>m.eliteSummon).length,2);});
test('elite unique drops stay on ground with a full bag, duplicates become ore',()=>{const g=arena();while(g.countSlots()<15)g.state.expedition.cards.push(g.makeCard('bread'));const m=add(g,'elite_overseer');g.killMonster(m);const t=g.tile(33,30);assert.equal(t.cards.length,1);assert.equal(t.cards[0].id,'elite_pick');g.state.player.x=33;assert.equal(g.takeCard(t.cards[0].uid),false);assert.equal(t.cards.length,1);g.killMonster(add(g,'elite_overseer'));assert.equal(t.cards.length,1);assert.ok(t.items.ore>=7);});
test('rock pick active has resource cost and cannot open guarded terrain',()=>{const g=arena(),v=wear(g,'elite_pick');g.tick=()=>{};g.tile(31,30).kind='rock';g.tile(32,30).kind='ore';assert.ok(g.act({type:'elite-active',item:'elite_pick',direction:[1,0]}));assert.equal(g.tile(31,30).kind,'floor');assert.equal(g.tile(32,30).kind,'floor');assert.equal(v.dur,175);assert.equal(g.state.player.dur,175);});
test('ember lamp fan, shield charge, cloak decoy, hook and tide active effects',()=>{let g=arena(),v=wear(g,'elite_lantern'),m=add(g,'elite_bell',31,30);g.tick=()=>{};assert.ok(g.eliteActive('elite_lantern',[1,0]));assert.equal(v.dur,115);assert.equal(m.hp,6);
 g=arena();v=wear(g,'elite_shield');m=add(g,'elite_bell',31,30);g.tick=()=>{};assert.equal(g.eliteActiveCheck('elite_shield').ok,false);g.monsterHit(m);assert.equal(v.charged,true);assert.ok(g.eliteActive('elite_shield',[1,0]));assert.equal(m.hp,5);assert.equal(v.charged,false);
 g=arena();v=wear(g,'elite_cloak');g.tick=()=>{};assert.ok(g.eliteActive('elite_cloak',[1,0]));assert.equal(g.state.player.x,32);assert.equal(g.state.eliteDecoys[0].x,30);assert.equal(v.charges,11);
 g=arena();v=wear(g,'elite_hook');g.tile(32,30).light={id:'lamp',dur:100,max:160,permanent:true};g.tile(32,30).torch=true;g.state.lightCache=null;g.state.visionCache=null;m=add(g,'elite_bell',34,30);m.plan={kind:'elite_hammer'};g.tick=()=>{};assert.ok(g.eliteActive('elite_hook',[1,0]));assert.equal(m.x,32);assert.equal(m.plan,null);assert.equal(v.charges,15);
 g=arena();g.setAmount('elite_tide',3);m=add(g,'elite_bell',31,30);g.tick=()=>{};assert.ok(g.eliteActive('elite_tide',[1,0]));assert.equal(m.x,32);assert.equal(m.hp,7);assert.equal(g.amount('elite_tide'),2);
});
test('active interrupts ordinary melee, lamp burns and resources serialize',()=>{const g=arena(),v=wear(g,'elite_lantern'),m=add(g,'undead',31,30);g.planMelee(m);g.state.player.armor=0;g.eliteActive('elite_lantern',[1,0]);assert.equal(g.state.player.hp,6);assert.equal(v.dur,114);const save=JSON.parse(JSON.stringify(E.encodeSave(g.exportCampaign()))),h=new E(7);h.enableCards();assert.ok(h.restoreCampaign(E.decodeSave(save)));assert.equal(h.state.player.inventoryGear.elite_lantern.dur,114);});
test('elite UI exposes six distinct canvas forms, hot ground and equipped active controls',()=>{assert.ok(html.includes('function drawElite'));assert.ok(html.includes('function eliteAbilityMarkup'));assert.ok(html.includes('data-ability-card'));assert.ok(html.includes('热地 '));assert.ok(html.includes('EscapeEngine.ELITES[m.type]?.text')); });
test('pick hits a pushed elite only once per activation',()=>{const g=arena();wear(g,'elite_pick');g.tick=()=>{};const m=add(g,'elite_bell',31,30);g.eliteActive('elite_pick',[1,0]);assert.equal(m.hp,6);assert.equal(m.x,32);});
test('priest illusion can be attacked to prevent pending swap',()=>{const g=arena(),m=add(g,'elite_priest',33,30);g.sense=()=>true;g.dungeonTurn(m);const a=m.illusion;assert.ok(a);const before={x:m.x,y:m.y};g.state.player.x=a.x-1;g.state.player.y=a.y;g.tick=()=>{};assert.ok(g.act({type:'move',dx:1,dy:0}));assert.equal(m.swapCancelled,true);assert.equal(g.state.eliteDecoys.length,0);g.resolveDungeonPlan(m,m.plan,2);assert.equal(m.x,before.x);assert.equal(m.y,before.y);});
test('all five unique gear resources can be repaired in stock and inventory',()=>{const g=arena();for(const id of Object.keys(E.ELITE_GEAR).filter(id=>id!=='elite_tide')){const c=g.makeCard(id),d=E.ELITE_GEAR[id];c.data[d.resource]=0;g.campaign.stock.push(c);assert.equal(g.stockRepairQuote(c.uid).gain,d.initial);g.state.player.inventoryGear[id]=c.data;assert.equal(g.repairQuote(id).gain,d.initial);}});
test('echo shield releases charged wave on next melee',()=>{const g=arena(),v=wear(g,'elite_shield'),m=add(g,'elite_bell',31,30),other=add(g,'elite_overseer',30,31);other.id=1000;g.tick=()=>{};g.monsterHit(m);assert.ok(v.charged);const hp=other.hp;g.strikeMonster(m);assert.equal(v.charged,false);assert.equal(other.hp,hp-2);});
test('tide is a three-use supply card consumed through normal use and drops again',()=>{const g=arena(),c=g.makeCard('elite_tide',3);assert.equal(c.type,'supply');assert.equal(E.EQUIPMENT.elite_tide,undefined);g.receiveCard(c);g.tick=()=>{};for(let i=0;i<3;i++)assert.ok(g.act({type:'use',item:'elite_tide'}));assert.equal(g.amount('elite_tide'),0);assert.ok(!g.state.expedition.cards.some(c=>c.id==='elite_tide'));g.killMonster(add(g,'elite_mother'));g.killMonster(add(g,'elite_mother'));assert.equal(g.tile(33,30).cards.filter(c=>c.id==='elite_tide').length,2);});
test('ember lamp placement doubles fuel, creates omnidirectional ground light and cannot be reclaimed',()=>{const g=arena(),v=wear(g,'elite_lantern');v.dur=17;g.tick=()=>{};const card=g.state.expedition.cards.find(c=>c.id==='elite_lantern');assert.ok(g.act({type:'light-place',item:'elite_lantern',uid:card.uid}));const t=g.tile(30,30);assert.equal(t.light.id,'elite_lantern');assert.equal(t.light.dur,34);assert.equal(g.state.player.equipped.off,null);assert.equal(g.state.player.inventoryGear.elite_lantern,undefined);assert.ok(!g.state.expedition.cards.includes(card));assert.equal(g.placeableLight('elite_lantern'),null);assert.equal(g.groundCards().length,0);assert.ok(g.lightLevel(28,30)>=2);assert.ok(g.lightLevel(32,30)>=2);assert.ok(g.lightLevel(30,28)>=2);assert.ok(g.lightLevel(30,32)>=2);});
test('ember clearing centered on player does not clear smoke behind wall',()=>{const g=arena();wear(g,'elite_lantern');g.tick=()=>{};g.tile(31,30).kind='wall';g.addFog(32,30,0,10,'smoke');assert.ok(g.fogAt(32,30)>0);const before={turn:g.state.turn,dur:g.state.player.inventoryGear.elite_lantern.dur};assert.equal(g.eliteActive('elite_lantern',[1,0]),false);assert.equal(g.state.turn,before.turn);assert.equal(g.state.player.inventoryGear.elite_lantern.dur,before.dur);assert.ok(g.fogAt(32,30)>0);});
test('swift melee priority damage remains visible during elite active action',()=>{const g=arena();wear(g,'elite_lantern');const m=add(g,'bat',31,30);g.planMelee(m);g.state.player.armor=0;g.state.visualEvents=[{actor:'stale',kind:'hurt'}];assert.ok(g.eliteActive('elite_lantern',[1,0]));assert.equal(g.state.player.hp,5);assert.ok(g.state.visualEvents.some(e=>e.actor==='player'&&e.kind==='hurt'&&e.damage===1));assert.ok(!g.state.visualEvents.some(e=>e.actor==='stale'));});
test('line elites reposition toward diagonal targets and short-range elites approach first',()=>{const g=arena(),s=g.state,p=s.player;s.params.vision=0;for(const type of ['elite_overseer','elite_priest','elite_ferryman']){s.monsters=[];const m=add(g,type,32,32);m.home={x:32,y:32};m.facing=[-1,0];g.dungeonTurn(m);assert.equal(m.plan,null,type+' must align before locking a line');assert.ok(m.x!==32||m.y!==32,type+' should approach');}for(const type of ['elite_stoker','elite_mother']){s.monsters=[];const m=add(g,type,34,30);m.home={x:34,y:30};m.facing=[-1,0];g.dungeonTurn(m);assert.equal(m.plan,null,type+' must enter skill range');assert.ok(m.x<34,type+' should approach');}});
