const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const html=fs.readFileSync(process.env.MINE5_HTML||process.argv[2]||require('node:path').join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;

const loot=g=>g.state.sites.filter(a=>a.container);
const signature=g=>JSON.stringify(loot(g).map(a=>[a.id,a.container,a.equipment,(a.cards||[]).map(c=>[c.id,c.qty]),a.quest]));
function start(seed=42,level=0){const g=new E(seed);g.enableCards();g.startExpedition(g.campaign.preparedIds,level);return g;}
test('boxes contain at most two rewards and one small supply stack, with varied finds on every floor',()=>{
 for(const level of [0,1,2]){const g=start(42,level),gears=[],types=new Set();for(const a of loot(g)){const entries=Object.entries(a.container).filter(([,n])=>n>0),cards=a.cards||[];assert(entries.length+cards.length+a.equipment.length+Number(!!a.quest)<=2,a.id+' has too much loot');const supplies=[...entries.filter(([id])=>id!=='ore').map(([id,qty])=>({id,qty})),...cards.filter(c=>c.type==='supply')];assert(supplies.length<=1,a.id+' repeats supplies');assert(supplies.every(c=>c.qty<=2));for(const c of cards)types.add(c.type);if(entries.some(([id])=>id==='ore'))types.add('ore');if(a.equipment.length)types.add('gear');gears.push(...a.equipment,...cards.filter(c=>c.type==='gear').map(c=>c.id));}assert.equal(new Set(gears).size,gears.length);assert.deepEqual([...types].filter(t=>['gear','buff','ore'].includes(t)).sort(),['buff','gear','ore']);assert(!gears.some(id=>id.startsWith('elite_')));assert(g.state.sites.find(a=>a.id==='risk-cache').equipment.length>0);if(level===0)assert(g.state.sites.find(a=>a.id==='workshop').quest);}
});
test('loot is deterministic, seeded once, and collecting a chest never refills it',()=>{const a=start(101),b=start(101);assert.equal(signature(a),signature(b));const box=loot(a).find(x=>x.id==='camp-supplies');box.searched=true;box.container={};box.cards=[];box.equipment=[];const before=signature(a);a.seedCommonSupplies();assert.equal(signature(a),before);assert.notEqual(signature(b),signature(start(202)));});
test('claimed and equipped gear do not respawn, full bags leave cards in the chest',()=>{const g=start(),s=g.state;const all=Object.keys(E.EQUIPMENT).filter(id=>id!=='torch');for(const id of all)s.claimedGear[id]=true;g.load(1);assert(loot(g).every(a=>!a.equipment.length&&!(a.cards||[]).some(c=>c.type==='gear')));const box=loot(g).find(a=>a.cards?.length);s.mode='playing';s.player.x=box.x;s.player.y=box.y;s.monsters=[];box.searched=true;s.lootId=box.id;while(g.countSlots()<15)assert(g.receiveCard(g.makeCard('bread',1)));const card=box.cards[0];assert.equal(g.lootCard(card.uid),false);assert(box.cards.includes(card));s.expedition.cards.pop();assert(g.lootCard(card.uid));assert(!box.cards.includes(card));});
