const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const ctx=vm.createContext({console});for(const m of fs.readFileSync(path.join(__dirname,'mine5.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function ready(){const g=new E(12345);g.enableCards();g.campaign.stock=['kit','bread','bomb','rope','quiet','rune'].map(id=>g.makeCard(id));g.campaign.preparedIds=[];return g;}
function start(ids=['kit','bread','bomb','rope','quiet'],level=0){const g=ready(),cards=ids.map(id=>g.campaign.stock.find(c=>c.id===id).uid);assert.equal(g.startExpedition(cards,level,0),true);g.state.monsters=[];return g;}
function unpack(g){const c=g.state.expedition.cards.find(c=>c.id==='kit');assert.equal(g.act({type:'card-unpack',uid:c.uid}),true);}
function fill(g){while(g.countSlots()<15)g.receiveCard(g.makeCard('bread',1));}
test('departure accepts at most five existing cards and removes only selected stock',()=>{const g=ready(),before=JSON.stringify(g.campaign),ids=g.campaign.stock.map(c=>c.uid);assert.equal(g.startExpedition(ids,0,0),false);assert.equal(JSON.stringify(g.campaign),before);assert.equal(g.startExpedition([ids[0],ids[0]],0,0),false);assert.equal(g.startExpedition(['missing'],0,0),false);assert.equal(g.startExpedition(ids.slice(0,5),0,0),true);assert.equal(g.countSlots(),5);assert.equal(g.campaign.stock.length,ids.length-5);assert.equal(g.state.player.equipped.main,null);});
test('starter kit expands into four equipped objects and frees its card slot',()=>{const g=start();unpack(g);const p=g.state.player;assert.equal(p.equipped.main,'normal');assert.equal(p.equipped.head,'helmet');assert.equal(p.equipped.body,'clothes');assert.equal(p.equipped.off,'torch');assert.equal(g.countSlots(),4);assert.equal(g.amount('torch'),1);assert.equal(g.state.expedition.cards.some(c=>c.id==='kit'),false);});
test('consuming a specific partial bread card preserves other cards, then discard and reclaim preserves charge',()=>{const g=start();unpack(g);g.state.mode='playing';g.state.player.hp=1;const c=g.state.expedition.cards.find(c=>c.id==='bread');g.receiveCard(g.makeCard('bread',2));assert.equal(g.act({type:'use',item:'bread',cardUid:c.uid}),true);assert.equal(c.qty,2);g.state.player.hp=1;assert.equal(g.act({type:'use',item:'bread',cardUid:c.uid}),true);assert.equal(c.qty,1);assert.equal(g.amount('bread'),3);assert.equal(g.dropCard(c.uid),true);assert.equal(g.amount('bread'),2);assert.equal(g.takeCard(c.uid),true);assert.equal(g.amount('bread'),3);});
test('fifteen card limit includes spare equipment and buffs, manual merge conserves quantities',()=>{const g=start();unpack(g);fill(g);assert.equal(g.receiveCard(g.makeCard('bomb',3)),false);assert.equal(g.acquireEquipment('sword'),false);const n=g.amount('bread');assert.equal(g.organizeCards(),true);assert.equal(g.amount('bread'),n);assert.ok(g.countSlots()<15);assert.equal(g.acquireEquipment('sword'),true);});
test('equipment transfer respects full pack and preserves wear',()=>{const g=start();unpack(g);g.acquireEquipment('sword');g.acquireEquipment('shield');assert.equal(g.equipGear('off','sword'),true);g.state.player.swordDur=12;g.saveEquipment();fill(g);assert.equal(g.equipGear('off',null),false);assert.equal(g.equipGear('off','shield'),true);assert.equal(g.countSlots(),15);assert.equal(g.equipGear('off','sword'),true);assert.equal(g.state.player.swordDur,12);});
test('kit expansion is atomic when slots are occupied and the pack has no room',()=>{const g=start();for(const id of ['heavy','lamp','anchor','sword']){g.acquireEquipment(id);g.equipGear(E.EQUIPMENT[id].slot,id);}fill(g);const c=g.state.expedition.cards.find(c=>c.id==='kit'),before=JSON.stringify(g.state.expedition.cards);assert.equal(g.unpackKit(c.uid),false);assert.equal(JSON.stringify(g.state.expedition.cards),before);});
test('carried buffs apply once and stop immediately when dropped',()=>{const g=start(['kit','bread','quiet']);unpack(g);g.state.params.digNoise=0;assert.equal(g.digNoise(6),4);g.receiveCard(g.makeCard('quiet'));assert.equal(g.digNoise(6),4);g.state.mode='playing';for(const c of [...g.state.expedition.cards].filter(c=>c.id==='quiet'))g.dropCard(c.uid);assert.equal(g.digNoise(6),6);});
test('successful extraction returns condition and charges once, then another expedition uses the same stock',()=>{const g=start();unpack(g);g.state.player.dur=22;g.setAmount('bread',1);g.state.ore=9;g.settleExpedition(true);const count=g.campaign.stock.length;assert.equal(g.campaign.stock.find(c=>c.id==='normal').data.dur,22);assert.equal(g.campaign.stock.find(c=>c.id==='bread').qty,1);assert.equal(g.campaign.ore,13);g.settleExpedition(true);assert.equal(g.campaign.stock.length,count);g.returnToCamp();const c=g.campaign.stock.find(c=>c.id==='normal');assert.equal(g.startExpedition([c.uid],1,0),true);assert.equal(g.equipGear('main','normal'),true);assert.equal(g.state.player.dur,22);});
test('death loses only expedition possessions and leaves a viable next departure',()=>{const g=start();const remaining=JSON.stringify(g.campaign.stock),ore=g.campaign.ore;g.fail('test');assert.equal(JSON.stringify(g.campaign.stock),remaining);assert.equal(g.campaign.ore,ore);g.returnToCamp();assert.ok(g.campaign.stock.some(c=>c.id==='kit'));assert.ok(g.campaign.stock.some(c=>c.id==='bread'));assert.equal(g.state.expedition.phase,'prepare');});
test('save restore conserves expedition cards, gear wear, ground cards and camp stock',()=>{const g=start();unpack(g);g.state.player.dur=43;g.state.mode='playing';g.dropCard(g.state.expedition.cards.find(c=>c.id==='bread').uid);const save=JSON.parse(JSON.stringify(g.exportCampaign())),h=ready();assert.equal(h.restoreCampaign(save),true);assert.equal(h.state.player.dur,43);assert.equal(h.countSlots(),g.countSlots());assert.equal(h.groundCards().length,1);assert.equal(h.campaign.stock.length,g.campaign.stock.length);h.settleExpedition(true);assert.equal(h.campaign.stock.find(c=>c.id==='normal').data.dur,43);});
test('each unlocked near exit descends without settling the expedition',()=>{for(let n=0;n<3;n++){const g=start(['kit','bread'],n);unpack(g);const s=g.state;s.mode='playing';s.challenge.complete=true;if(n===2){s.challenge.high=true;s.challenge.low=true;s.turn=1;}const a=s.sites.find(a=>a.id==='mechanical');s.player.x=a.x;s.player.y=a.y;a.discovered=true;s.routeChoice=a.id;s.visionCache=null;g.reveal();assert.equal(g.act({type:'choose',kind:'depart'}),true);assert.equal(g.state.mode,'home');assert.equal(g.state.level,(n+1)%3);assert.equal(g.state.depth,2);assert.equal(g.state.expedition.phase,'active');assert.equal(g.campaign.clears,0);}});

test('stored sword retains its durability on departure',()=>{const g=ready(),c=g.makeCard('sword',1,{dur:17});g.campaign.stock.push(c);assert.equal(g.startExpedition([c.uid],0,0),true);assert.equal(g.state.player.inventoryGear.sword.dur,17);assert.equal(g.equipGear('off','sword'),true);assert.equal(g.state.player.swordDur,17);});

test('restored noise fields remain usable for monster hearing on the saved turn',()=>{const g=start();unpack(g);g.state.mode='playing';g.emitNoise(g.state.player.x,g.state.player.y,12,'dig');g.noiseField(g.state.noises.at(-1));const h=ready();h.restoreCampaign(JSON.parse(JSON.stringify(g.exportCampaign())));const field=h.noiseField(h.state.noises.at(-1));assert.equal(typeof field.get,'function');});

test('camp repairs the returned broken shield without changing its identity or other supplies',()=>{const g=start();unpack(g);g.acquireEquipment('shield');g.state.player.inventoryGear.shield.dur=0;g.state.ore=10;g.settleExpedition(true);g.returnToCamp();const c=g.campaign.stock.find(c=>c.id==='shield'),before=g.campaign.ore,bread=g.campaign.stock.filter(c=>c.id==='bread').reduce((n,c)=>n+c.qty,0);assert.equal(g.repairStock(c.uid),true);assert.equal(c.data.dur,6);assert.equal(g.campaign.ore,before-3);assert.equal(g.campaign.stock.filter(c=>c.id==='shield').length,1);assert.equal(g.campaign.stock.filter(c=>c.id==='bread').reduce((n,c)=>n+c.qty,0),bread);assert.equal(g.startExpedition([c.uid],0,0),true);g.equipGear('off','shield');assert.equal(g.hasHand('shield'),true);});

test('new campaign rolls unique gear in camp and prepares only bread and kit',()=>{const profiles=[];for(const seed of [11,22,33]){const g=new E(seed);g.enableCards();const p=g.campaign,prepared=p.preparedIds.map(uid=>p.stock.find(c=>c.uid===uid));assert.deepEqual(Array.from(prepared,c=>c.id).sort(),['bread','kit']);const chest=p.stock.filter(c=>!p.preparedIds.includes(c.uid));assert.equal(chest.length,8);const gear=chest.filter(c=>c.type==='gear').map(c=>c.id);assert.equal(new Set(gear).size,gear.length);assert.ok(chest.every(c=>c.type!=='supply'||c.qty>=1&&c.qty<=3));profiles.push(JSON.stringify(p.stock));const h=new E(seed);h.enableCards();assert.equal(JSON.stringify(h.campaign),JSON.stringify(p));}assert.equal(new Set(profiles).size,3);});
test('restoring and returning to camp never rerolls or resets the prepared selection',()=>{const g=ready();g.campaign.preparedIds=[g.campaign.stock[1].uid];const before=JSON.stringify(g.campaign),h=ready();h.restoreCampaign(JSON.parse(JSON.stringify(g.exportCampaign())));assert.equal(JSON.stringify(h.campaign),before);g.startExpedition(g.campaign.preparedIds,0,0);g.settleExpedition(true);const after=JSON.stringify(g.campaign.stock);g.returnToCamp();assert.equal(JSON.stringify(g.campaign.stock),after);assert.equal(g.campaign.preparedIds.length,0);});

test('camp actions clear the previous movement animation before their own events are added',()=>{const g=ready();g.visual('home-player','walk',{x:1,y:1},{x:0,y:1});g.state.effect={kind:'old'};assert.equal(g.act({type:'move',dx:0,dy:1}),true);assert.equal(g.state.visualEvents.length,0);assert.equal(g.state.effect,null);g.visual('home-player','walk',{x:0,y:1},{x:0,y:2});g.act({type:'home-select',x:0,y:2});assert.equal(g.state.visualEvents.length,0);assert.equal(g.act({type:'interact'}),true);assert.equal(g.state.panel,'loadout');});
test('free card actions never replay a previous attack or advance time',()=>{const g=start();g.state.mode='playing';g.visual('player','hurt',g.state.player,g.state.player);g.state.effect={kind:'old'};const turn=g.state.total;g.act({type:'card-organize'});assert.equal(g.state.visualEvents.length,0);assert.equal(g.state.effect,null);assert.equal(g.state.total,turn);});
