const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');const html=fs.readFileSync(process.env.MINE5_HTML||path.join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(match[1]);if(!match[1].includes('canvas=$'))vm.runInContext(match[1],ctx);}const E=ctx.EscapeEngine;
function arena(){const g=new E(12345);g.enableCards();g.startExpedition(g.campaign.preparedIds);const s=g.state;s.mode='playing';s.monsters=[];s.sites=[];s.player.x=30;s.player.y=30;s.player.hp=6;s.player.armor=0;s.player.facing=[1,0];s.player.equipped={main:null,body:null,head:null,off:null};s.player.inventoryGear={};s.expedition.cards=[];s.expedition.torchHand=0;s.params.vision=0;s.logs=[];s.visualEvents=[];s.environment.clouds=[];s.environment.cleared=[];for(let y=20;y<=40;y++)for(let x=20;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',fog:null,torch:false,light:null,collapseAt:null});s.lightCache=null;s.visionCache=null;return g;}
function add(g,type,x=31,y=30){const m=g.createMonster(type,x,y,900);g.state.monsters.push(m);return m;}
test('only visible, nonfrozen, nonexpired real plans qualify for warning',()=>{const g=arena(),m=add(g,'undead');assert.equal(g.monsterPlanVisible(m),false);g.planMelee(m);assert.equal(g.monsterPlanVisible(m),true);m.freeze=2;assert.equal(g.monsterPlanVisible(m),false);m.freeze=0;m.plan.due=g.state.turn-1;assert.equal(g.monsterPlanVisible(m),false);m.plan.due=g.state.turn+1;m.plan.cells=[];assert.equal(g.monsterPlanVisible(m),false);});
test('invisible normal and swift melee retain plans without advance warning logs',()=>{for(const swift of [false,true]){const g=arena(),m=add(g,'undead',33,30);m.swift=swift;assert.equal(g.monsterVisible(m),false);g.planMelee(m);assert.ok(m.plan);assert.equal(g.monsterPlanVisible(m),false);assert.equal(g.state.logs.length,0);}});
test('offscreen eel windup is quiet but damage and player hurt feedback remain',()=>{const g=arena(),m=add(g,'eel',33,30);assert.equal(g.planSpecial(m),true);assert.ok(m.plan);assert.equal(g.state.logs.length,0);g.resolvePlan(m,g.state.turn+1);assert.equal(g.state.player.hp,5);assert.ok(g.state.visualEvents.some(e=>e.actor==='player'&&e.kind==='hurt'&&e.damage===1));assert.ok(g.state.logs.some(l=>l.tone==='danger'));});
test('visible windup still announces attacks and retains skill fields',()=>{const g=arena(),m=add(g,'sentinel');assert.ok(g.planSpecial(m));assert.equal(m.plan.kind,'sweep');assert.equal(m.plan.cells.length,4);assert.ok(g.state.logs.some(l=>l.tone==='warn'));assert.equal(g.monsterPlanVisible(m),true);});
test('invisible dungeon skill does not log advance warning',()=>{const g=arena(),m=add(g,'alarm',33,30);g.dungeonTurn(m);assert.equal(m.plan?.kind,'alarm');assert.equal(g.state.logs.filter(l=>/鼓起鸣囊/.test(l.text)).length,0);});
test('idle attack overlays removed without changing inspection facts',()=>{assert.ok(!html.includes('function combatOverlay('));assert.ok(!html.includes("text('举镐区'"));assert.ok(html.includes('function monsterSenseSummary(m)'));assert.ok(html.includes('game.monsterPlanVisible(m,v)'));});
