const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const ctx=vm.createContext({console});for(const m of fs.readFileSync(process.env.MINE5_HTML||path.join(__dirname,'mine5.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}
const extension=path.join(__dirname,'mine5.encounters-v3.js');if(fs.existsSync(extension))vm.runInContext(fs.readFileSync(extension,'utf8'),ctx);const E=ctx.EscapeEngine;
function arena(){const g=new E(12345),s=g.state;s.mode='playing';s.monsters=[];s.hazards=[];s.bombs=[];s.sites=[];s.adventure={risk:null,ice:[],gates:[],tide:null};s.reactions={version:3,sites:[],pending:[],water:[]};Object.assign(s.player,{x:30,y:30,hp:8,maxHp:8,armor:0});for(let y=25;y<=40;y++)for(let x=25;x<=40;x++)Object.assign(g.tile(x,y),{kind:'floor',items:{},cards:[],quest:null,questItems:[],gate:null,challengeSafe:false,riskPassage:false,rail:null,tidal:false,collapseAt:null});return g;}
function reactor(g,kind,x=34,y=30){const a={id:'reaction-'+kind,x,y,reactor:kind,reactorState:'armed',kind:'tablet',direction:[1,0],openCells:[[x,y]],description:'warning'};g.state.sites.push(a);g.state.reactions.sites.push(a.id);g.tile(x,y).reactor=kind;return a;}
test('guard is durable nonelite, dormant until breach, and loot locked until defeated',()=>{const g=new E(12345),s=g.state,r=s.adventure.risk,a=s.sites.find(a=>a.id==='risk-cache');assert.ok(r.guardState);const m=s.monsters.find(m=>m.id===r.guardState.guardId);assert.equal(m.elite,undefined);assert.ok(m.hp>=6);s.mode='playing';const hp=s.player.hp;g.dungeonTurn(m);assert.equal(m.plan,null);g.tile(r.neck.x,r.neck.y).kind='floor';g.adventureTurn();assert.equal(r.due,null);assert.ok(r.guardState.awakened);assert.ok(m.recoverUntil>=s.turn+1);assert.equal(s.player.hp,hp);s.player.x=a.x;s.player.y=a.y;a.searched=true;s.lootId=a.id;assert.equal(g.lootAll(),false);s.turn+=50;g.adventureTurn();assert.equal(r.collapsed,false);assert.ok(a.equipment.length);s.eliteBomb=true;g.killMonster(m);delete s.eliteBomb;assert.ok(s.monsters.includes(m));assert.equal(m.hp,3);g.eliteDamage(m,3);assert.ok(r.guardState.resolved);assert.ok(a.equipment.length);});
test('bomb gas is delayed bounded and idempotent',()=>{const g=arena(),s=g.state,a=reactor(g,'gas');g.explode({x:34,y:30});assert.equal(a.reactorState,'triggered');assert.equal(s.reactions.pending.length,1);const t=s.reactions.pending[0].due;g.triggerReaction(a,'blast');assert.equal(s.reactions.pending.length,1);s.player.x=34;s.turn=t-1;g.reactionTurn();assert.equal(s.player.hp,8);s.turn=t;g.reactionTurn();assert.equal(s.player.hp,7);assert.equal(s.reactions.pending.length,0);g.reactionTurn();assert.equal(s.player.hp,7);});
test('fire opens fungus once and preserves protected task tiles',()=>{const g=arena(),s=g.state,a=reactor(g,'fungus');g.tile(a.x,a.y).kind='hard';const q={id:'task-test',x:35,y:30,questSource:true};s.sites.push(q);g.tile(q.x,q.y).kind='hard';a.openCells.push([q.x,q.y]);assert.equal(g.triggerReaction(a,'fire'),true);assert.equal(g.tile(a.x,a.y).kind,'floor');assert.equal(g.tile(q.x,q.y).kind,'hard');const n=s.environment.clouds.length;assert.equal(g.triggerReaction(a,'fire'),false);assert.equal(s.environment.clouds.length,n);});
test('reservoir moves ordinary loose loot and creatures one step, never task items or exits',()=>{const g=arena(),s=g.state,a=reactor(g,'reservoir');a.flowCells=[[35,30],[36,30],[37,30]];g.tile(35,30).items={ore:2,questToken:1};const m=g.createMonster('skeleton',35,30,999);s.monsters=[m];s.sites.push({id:'mechanical',x:37,y:30,exitRole:'near'});assert.equal(g.triggerReaction(a,'breach'),true);assert.equal(m.x,36);assert.equal(g.tile(35,30).items.questToken,1);assert.equal(g.tile(36,30).items.ore,2);assert.equal(g.tile(37,30).kind,'floor');assert.equal(g.tile(37,30).reactionWaterUntil,undefined);assert.ok(g.passable(35,30));});
test('charge opens weak support without creating obstruction or touching gates',()=>{const g=arena(),a=reactor(g,'support');g.tile(34,30).kind='rock';a.openCells.push([35,30]);Object.assign(g.tile(35,30),{kind:'hard',gate:1});assert.equal(g.triggerReaction(a,'charge'),true);assert.equal(g.tile(34,30).kind,'floor');assert.equal(g.tile(35,30).kind,'hard');});
test('seeded reactions are deterministic bounded and warning sites are reachable',()=>{const a=new E(54321),b=new E(54321);assert.ok(a.state.reactions);assert.equal(JSON.stringify(a.state.reactions),JSON.stringify(b.state.reactions));assert.ok(a.state.reactions.sites.length>=3);assert.ok(a.state.reactions.sites.length<=4);const reach=a.reachSet(a.state.layout.start.x,a.state.layout.start.y);for(const id of a.state.reactions.sites){const site=a.state.sites.find(s=>s.id===id);assert.ok(a.standingNear(reach,site),id);assert.match(site.description,/火|爆|冲|水/);}});
test('normal torch action ignites a neighboring membrane through gameplay',()=>{const g=arena(),s=g.state,a=reactor(g,'fungus',31,30);g.tile(31,30).kind='hard';s.player.hands=['pick','torch'];s.bag.torch=2;g.tile(30,30).torch=false;assert.equal(g.act({type:'use',item:'torch'}),true);assert.equal(a.reactorState,'triggered');assert.equal(g.tile(31,30).kind,'floor');});
test('charge resolution triggers the support in its traversed cells',()=>{const g=arena(),a=reactor(g,'support');g.tile(a.x,a.y).kind='rock';const m=g.createMonster('beetle',33,30,500,[1,0]);g.state.monsters=[m];g.resolveDungeonPlan(m,{kind:'elite_charge',origin:{x:33,y:30},direction:[1,0],cells:[{x:34,y:30},{x:35,y:30}]},g.state.turn);assert.equal(a.reactorState,'triggered');assert.equal(g.tile(34,30).kind,'floor');});
test('pending gas and water remain bounded and stable when restored',()=>{const g=arena(),s=g.state,a=reactor(g,'gas');g.triggerReaction(a,'blast');const saved=JSON.parse(JSON.stringify(s.reactions));s.reactions=saved;s.turn++;g.reactionTurn();assert.equal(s.reactions.pending.length,0);g.reactionTurn();assert.equal(s.reactions.pending.length,0);});
test('cross-theme samples preserve every task and exit reachable before seeding',()=>{for(const seed of [1,42,2026])for(const theme of [0,1,2]){const g=new E(seed);if(theme)g.load(theme);const s=g.state,reach=g.reachSet(s.layout.start.x,s.layout.start.y);assert.ok(s.reactions.sites.length>=3,seed+'/'+theme);assert.ok(s.reactions.sites.length<=4);for(const a of s.sites.filter(a=>a.chapterDevice||a.questSource||a.exitRole||['home','miner','pump','workshop','shrine'].includes(a.id)))assert.ok(g.standingNear(reach,a),seed+'/'+theme+'/'+a.id);assert.equal(s.monsters.filter(m=>m.elite).length,2);const before=JSON.stringify(s.reactions);g.seedReactions();assert.equal(JSON.stringify(s.reactions),before);}});
test('offscreen gas stays quiet but emits a single finite blast noise',()=>{const g=arena(),s=g.state,a=reactor(g,'gas'),warnings=[],noises=[];g.visible=()=>new Set();g.log=(text,kind)=>{if(kind==='warn')warnings.push(text)};g.emitNoise=(...args)=>noises.push(args);g.triggerReaction(a,'blast');s.turn++;g.reactionTurn();g.reactionTurn();assert.equal(warnings.length,0);assert.equal(noises.length,1);assert.equal(noises[0][3],'blast');});
test('reservoir carries loose supply cards while preserving quest cards',()=>{const g=arena(),a=reactor(g,'reservoir');a.flowCells=[[35,30],[36,30]];g.tile(35,30).cards=[{uid:'loose',id:'bread',type:'supply',qty:1},{uid:'quest',id:'repair-part',type:'quest'}];g.triggerReaction(a,'breach');assert.equal(g.tile(36,30).cards[0]?.uid,'loose');assert.equal(g.tile(35,30).cards[0]?.uid,'quest');});

test('legacy collapsed and exhausted caches never regenerate a rewardless guardian',()=>{const g=new E(12345),s=g.state,r=s.adventure.risk,a=s.sites.find(a=>a.id==='risk-cache');s.monsters=s.monsters.filter(m=>!m.guardSiteKey);r.collapsed=true;r.spotted=true;delete r.guardState;a.container={};a.equipment=[];a.cards=[];a.searched=true;g.seedGuardedCache();assert.equal(r.collapsed,true);assert(r.guardState.resolved);assert(!s.monsters.some(m=>m.guardSiteKey));assert.match(g.riskEncounterStatus(),/坍塌/);});
