const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const ctx=vm.createContext({console});
for(const m of fs.readFileSync(path.join(__dirname,'mine5.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}
const E=ctx.EscapeEngine;
function game(level=0,seed=12345){const g=new E(seed);if(level)g.load(level);g.state.mode='playing';g.state.monsters=[];return g;}
function approach(g,id){const a=g.state.sites.find(a=>a.id===id);assert.ok(a);Object.assign(g.state.player,{x:a.x,y:a.y});a.discovered=true;return a;}
function activate(g,id){g.state.challenge.read=true;g.state.challenge.order=[id,...['hammer','lamp','wave'].filter(k=>k!==id)];approach(g,'rune-'+id);return g.act({type:'choose',kind:'chapter:rune:'+id});}
for(const [slot,item] of [['main','heavy'],['head','helmet'],['body','anchor']])test('underground '+slot+' change spends one turn and preserves wear',()=>{const g=game(),p=g.state.player;g.acquireEquipment(item);const old=p.dur;assert.equal(g.act({type:'equip-gear',slot,item}),true);assert.equal(g.state.turn,1);assert.equal(p.equipped[slot],item);assert.equal(p.inventoryGear.normal.dur,old);});
test('camp and offhand swaps remain free; invalid and repeated choices are free',()=>{const g=game();g.acquireEquipment('heavy');g.acquireEquipment('sword');g.state.mode='home';assert.equal(g.act({type:'equip-gear',slot:'main',item:'heavy'}),true);g.state.mode='playing';assert.equal(g.act({type:'equip-gear',slot:'off',item:'sword'}),true);assert.equal(g.act({type:'equip-gear',slot:'main',item:'heavy'}),false);assert.equal(g.act({type:'equip-gear',slot:'head',item:'heavy'}),false);assert.equal(g.state.turn,0);});
test('unequipping underground advances time and numeric equip cannot bypass cost',()=>{const g=game();g.acquireEquipment('heavy');g.act({type:'equip',slot:0,item:'heavy'});assert.equal(g.state.turn,1);g.act({type:'equip-gear',slot:'body',item:null});assert.equal(g.state.turn,2);});
test('stun spends a turn without applying a paid equipment change',()=>{const g=game();g.acquireEquipment('helmet');g.state.player.stun=1;assert.equal(g.act({type:'equip-gear',slot:'head',item:'helmet'}),true);assert.equal(g.state.turn,1);assert.equal(g.state.player.stun,0);assert.equal(g.state.player.equipped.head,null);});
test('priority strike can kill before paid equipment takes effect',()=>{const g=game(),s=g.state,p=s.player;p.x=30;p.y=30;p.hp=1;p.armor=0;for(let y=29;y<=31;y++)for(let x=29;x<=31;x++)Object.assign(g.tile(x,y),{kind:'floor',gate:null});g.acquireEquipment('anchor');const m=g.createMonster('bat',31,30,100,[-1,0]);s.monsters=[m];g.planMelee(m);g.act({type:'equip-gear',slot:'body',item:'anchor'});assert.equal(s.mode,'dead');assert.equal(p.equipped.body,'clothes');assert.equal(s.turn,1);});
test('hammer opens sealed shortcut and emits a real sound',()=>{const g=game(1),s=g.state;s.layout.shrineCells=[[30,30]];Object.assign(g.tile(30,30),{kind:'hard',cracks:0,gate:null});activate(g,'hammer');assert.equal(g.passable(30,30),true);assert.ok(s.noises.some(n=>n.kind==='mechanism'));assert.equal(s.turn,1);});
test('lamp lights the hall and calls existing guards to the sound',()=>{const g=game(1),s=g.state,a=approach(g,'rune-lamp');for(let y=a.y-3;y<=a.y+3;y++)for(let x=a.x-3;x<=a.x+3;x++)Object.assign(g.tile(x,y),{kind:'floor',torch:false,gate:null,region:a.region});const m=g.createMonster('sentinel',a.x+3,a.y,100,[1,0]);s.monsters=[m];activate(g,'lamp');assert.equal(g.tile(a.x,a.y).torch,true);assert.ok(s.map.tiles.filter(t=>t.region===a.region&&t.torch).length>1);assert.ok(m.alert>0);assert.equal(s.monsters.length,1);});
test('wave drains water, keeps built bridges and unlocks flooded storage',()=>{const g=game(1),s=g.state;s.layout.drainedCells=[[30,30],[31,30]];g.tile(30,30).kind='water';g.tile(31,30).kind='bridge';activate(g,'wave');assert.equal(g.tile(30,30).kind,'floor');assert.equal(g.tile(31,30).kind,'bridge');assert.equal(s.local.drained,true);assert.equal(s.sites.find(a=>a.id==='pump').done,true);});
test('wrong seals reset the current round without retriggering environmental rewards',()=>{const g=game(1),s=g.state,c=s.challenge;c.read=true;c.order=['hammer','lamp','wave','hammer','lamp','wave'];let effects=0;const apply=g.applyRuneEffect;g.applyRuneEffect=function(...args){effects++;return apply.apply(this,args);};approach(g,'rune-hammer');g.act({type:'choose',kind:'chapter:rune:hammer'});approach(g,'rune-wave');g.act({type:'choose',kind:'chapter:rune:wave'});assert.equal(c.progress,0);assert.equal(s.local.drained,false);assert.equal(s.sites.find(a=>a.id==='rune-hammer').done,false);const turn=s.turn;approach(g,'rune-hammer');assert.equal(g.act({type:'choose',kind:'chapter:rune:hammer'}),true);assert.equal(effects,1);assert.equal(s.turn,turn+1);for(const id of c.order.slice(c.progress)){approach(g,'rune-'+id);g.act({type:'choose',kind:'chapter:rune:'+id});}assert.equal(c.complete,true);assert.equal(effects,3);});
test('city effects keep devices and exits reachable across all seed variants',()=>{for(let seed=1;seed<=12;seed++){const g=game(1,seed),s=g.state,c=s.challenge;c.read=true;for(const id of c.order){approach(g,'rune-'+id);g.act({type:'choose',kind:'chapter:rune:'+id});const seen=g.reachSet(s.player.x,s.player.y);for(const a of s.sites.filter(a=>a.chapterDevice||['water','mechanical'].includes(a.id)))assert.ok(g.standingNear(seen,a),seed+'/'+id+'/'+a.id);}assert.equal(c.complete,true);}});

test('seeded cities provide an unopened hammer shortcut before any seal is activated',()=>{for(let seed=1;seed<=20;seed++){const g=game(1,seed),s=g.state;const cells=s.layout.shrineCells.filter(([x,y])=>['rock','hard','rubble'].includes(g.tile(x,y).kind)&&!g.tile(x,y).gate);assert.ok(cells.length,'no hammer shortcut in seed '+seed);activate(g,'hammer');for(const [x,y]of cells)assert.equal(g.passable(x,y),true,seed+'/'+x+','+y);}});
