const fs=require('fs'),vm=require('vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('path');const c=vm.createContext({console});for(const m of fs.readFileSync(path.join(__dirname,'mine5.html'),'utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(!m[1].includes('canvas=$'))vm.runInContext(m[1],c);const E=c.EscapeEngine;
function run(){const g=new E(17);g.enableCards();g.startExpedition(g.campaign.preparedIds);g.state.mode='playing';g.state.monsters=[];return g;}
test('wallet is independent of card counts and accepts all minerals when pack is full',()=>{const g=run();while(g.countSlots()<15)g.receiveCard(g.makeCard('bread'));g.addMineral('copper',20);g.addMineral('gold',2);assert.equal(g.mineralAmount('copper'),20);assert.equal(g.countSlots(),15);assert.equal(g.makeCard('wallet'),null);assert.equal(g.makeCard('gold'),null);assert.equal(g.receiveCard({id:'wallet',uid:'fake',type:'special'}),false);g.organizeCards();assert.equal(g.mineralAmount('gold'),2);});
test('wallet exchange is atomic and preserves silver spending APIs',()=>{const g=run(),ore=g.amount('ore');g.addMineral('gold',2);assert.equal(g.exchangeMineral('gold',3),false);assert.equal(g.mineralAmount('gold'),2);assert.equal(g.exchangeMineral('gold',-1),false);assert.equal(g.exchangeMineral('gold',2),true);assert.equal(g.amount('ore'),ore+8);assert.equal(g.mineralAmount('gold'),0);assert.equal(g.spend(3),true);assert.equal(g.mineralAmount('ore'),ore+5);});
test('minerals auto-collect from terrain without becoming supply cards',()=>{const g=run(),items=g.tile(g.state.player.x,g.state.player.y).items;Object.assign(items,{iron:3,crystal:1});assert.equal(g.collectItems(items,true),true);assert.equal(g.mineralAmount('iron'),3);assert.equal(items.iron,0);assert.equal(g.state.expedition.cards.some(c=>c.id==='iron'),false);});
test('wallet survives descent and save; extraction deposits once and death loses carried minerals',()=>{const g=run();g.addMineral('gold',3);g.load(1);assert.equal(g.mineralAmount('gold'),3);const save=JSON.parse(JSON.stringify(E.encodeSave(g.exportCampaign()))),h=new E(1);assert.ok(h.restoreCampaign(E.decodeSave(save)));assert.equal(h.mineralAmount('gold'),3);assert.ok(h.settleExpedition(true));assert.equal(h.campaign.wallet.gold,3);assert.equal(h.settleExpedition(true),false);h.returnToCamp();assert.equal(h.mineralAmount('gold'),3);h.startExpedition([]);assert.equal(h.mineralAmount('gold'),3);assert.equal(h.campaign.wallet.gold,0);h.settleExpedition(false);assert.equal(h.mineralAmount('gold'),0);});
test('generated veins include all four additional ores and old saves load empty wallet',()=>{const g=run(),kinds=new Set(g.state.map.tiles.filter(t=>t.kind==='ore').map(t=>t.mineral));for(const id of ['copper','iron','gold','crystal'])assert.ok(kinds.has(id),id);const save=JSON.parse(JSON.stringify(g.exportCampaign()));delete save.state.wallet;delete save.profile.wallet;const h=new E(1);assert.ok(h.restoreCampaign(save));assert.equal(h.mineralAmount('iron'),0);});
test('mining collects a single secondary mineral when stepping onto the opened vein',()=>{const g=run(),s=g.state;g.unpackKit(s.expedition.cards.find(c=>c.id==='kit').uid);s.player.x=30;s.player.y=30;for(let y=29;y<=31;y++)for(let x=29;x<=32;x++)Object.assign(g.tile(x,y),{kind:'floor',collapseAt:null,items:{}});const t=g.tile(31,30);Object.assign(t,{kind:'ore',mineral:'gold',cracks:0});for(let i=0;i<8&&t.kind==='ore';i++)g.act({type:'move',dx:1,dy:0});assert.equal(t.kind,'floor');assert.equal(s.player.x,31);assert.equal(g.mineralAmount('gold'),1);assert.equal(t.items.gold,0);g.collectItems(t.items,true);assert.equal(g.mineralAmount('gold'),1);});
test('bomb opening a vein during an unfinished mining action releases mineral only once',()=>{const g=run(),s=g.state;g.unpackKit(s.expedition.cards.find(c=>c.id==='kit').uid);s.player.x=30;s.player.y=30;s.player.dur=0;s.player.armor=10;for(let y=29;y<=31;y++)for(let x=29;x<=32;x++)Object.assign(g.tile(x,y),{kind:'floor',collapseAt:null,items:{}});const t=g.tile(31,30);Object.assign(t,{kind:'ore',mineral:'gold',cracks:0});s.bombs=[{x:31,y:30,due:s.turn+1}];g.act({type:'move',dx:1,dy:0});assert.equal(t.kind,'floor');assert.equal(t.items.gold,1);assert.equal(g.mineralAmount('gold'),0);});
test('individual ground mineral pickup and capacity ignore a full card pack',()=>{const g=run();while(g.countSlots()<15)g.receiveCard(g.makeCard('bread'));const t=g.tile(g.state.player.x,g.state.player.y);t.items.gold=4;assert.ok(g.capacity('gold')>=4);const turn=g.state.turn;assert.ok(g.act({type:'pickup',item:'gold'}));assert.equal(g.mineralAmount('gold'),4);assert.equal(t.items.gold,0);assert.equal(g.state.turn,turn);assert.equal(g.countSlots(),15);});
