const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(process.env.MINE5_HTML||path.join(__dirname,'mine5.html'),'utf8');
const ctx=vm.createContext({console});for(const m of source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine;
function start(theme=0){const g=new E(12345);g.enableCards();const ids=g.campaign.preparedIds;assert.equal(g.startExpedition(ids,theme,0),true);const kit=g.state.expedition.cards.find(c=>c.id==='kit');if(kit)g.unpackKit(kit.uid);g.state.mode='playing';g.state.monsters=[];return g;}
function approach(g,id){const s=g.state;let a=s.sites.find(a=>a.id===id);if(!a&&id==='random-exit'){a=s.sites.find(a=>a.id==='water');a.id=id;}assert.ok(a);a.exitRole=({mechanical:'near',water:'far','random-exit':'random'})[id];a.discovered=true;s.player.x=a.x;s.player.y=a.y;s.routeChoice=id;s.visionCache=null;s.monsters=[];return a;}
function depart(g,id='water'){approach(g,id);assert.equal(g.act({type:'interact'}),true);assert.equal(g.state.panel,'route');assert.equal(g.act({type:'choose',kind:'depart'}),true);}
test('only near exit requires each floor challenge, far and random bypass tasks and tide windows',()=>{for(const theme of [0,1,2])for(const id of ['mechanical','water','random-exit']){const g=start(theme);approach(g,id);g.state.turn=8;assert.equal(g.exitCheck().ok,id!=='mechanical',theme+' '+id);if(id==='mechanical'){g.state.challenge.complete=true;assert.equal(g.exitCheck().ok,theme!==2);g.state.turn=1;assert.equal(g.exitCheck().ok,true);}else{depart(g,id);assert.equal(g.state.depth,2);assert.equal(g.state.mode,'home');assert.equal(g.state.expedition.phase,'active');assert.equal(g.campaign.clears,0);}}});
test('all three exits can open their route panel before the near task is complete',()=>{for(const id of ['mechanical','water','random-exit']){const g=start();approach(g,id);g.state.routeChoice=null;assert.equal(g.act({type:'interact'}),true);assert.equal(g.state.routeChoice,id);assert.equal(g.state.panel,'route');}});
test('successive floors cycle the three themes with fresh seeds and reset local world state',()=>{const g=start(),seen=new Set(),seeds=new Set();for(let depth=1;depth<=5;depth++){const s=g.state;assert.equal(s.depth,depth);assert.equal(s.level,[0,1,2,0,1][depth-1]);const layout=JSON.stringify(s.layout.regions.map(r=>[r.cx,r.cy,r.rx,r.ry]));seen.add(layout);seeds.add(s.floorSeed);assert.equal(s.challenge.complete,false);assert.equal(s.local.part,false);if(depth<5){s.mode='playing';s.claimedParts[s.level]=true;s.local.part=true;s.notes.push({id:'old-floor'});depart(g);assert.equal(s.notes.some(n=>n.id==='old-floor'),false);assert.equal(s.bombs.length,0);assert.equal(s.hazards.length,0);}}assert.equal(seeds.size,5);assert.ok(seen.size>=4);assert.equal(g.state.routeHistory.length,4);});
test('descent keeps card identities, equipment wear, spare fuel, ore, total turns and unique gear ledger',()=>{const g=start(),s=g.state,p=s.player;g.acquireEquipment('sword');g.acquireEquipment('shield');g.receiveCard(g.makeCard('torch',2));const spare=s.expedition.cards.find(c=>c.id==='torch');spare.fuels=[17,29];p.dur=23;p.swordDur=14;p.inventoryGear.sword.dur=14;p.inventoryGear.shield.dur=1;s.expedition.torchDur=19;s.ore=9;s.total=71;g.saveEquipment();const uids=s.expedition.cards.map(c=>c.uid).join(','),stock=JSON.stringify(g.campaign.stock),equipped=JSON.stringify(p.equipped),gearLedger=JSON.stringify(s.claimedGear);depart(g);assert.equal(s.expedition.cards.map(c=>c.uid).join(','),uids);assert.equal(JSON.stringify(g.campaign.stock),stock);assert.equal(JSON.stringify(p.equipped),equipped);assert.equal(p.dur,23);assert.equal(p.inventoryGear.sword.dur,14);assert.equal(p.inventoryGear.shield.dur,1);assert.equal(s.expedition.torchDur,18);assert.equal(JSON.stringify(spare.fuels),'[17,29]');assert.equal(s.ore,9);assert.equal(s.total,72);assert.equal(JSON.stringify(s.claimedGear),gearLedger);for(const c of s.expedition.cards.filter(c=>c.type==='gear'))assert.equal(c.data,p.inventoryGear[c.id]);});
test('restore keeps current floor and rebuilds its manifest, then descends to the same deterministic next map',()=>{const g=start();depart(g);g.state.mode='playing';depart(g);const saved=JSON.parse(JSON.stringify(g.exportCampaign())),h=start();assert.equal(h.restoreCampaign(saved),true);assert.equal(h.state.depth,3);assert.equal(h.manifest.seed,h.state.floorSeed);assert.equal(h.manifest.code,h.state.code);assert.equal(JSON.stringify(h.manifest.chapter(h.state.level).regions),JSON.stringify(g.manifest.chapter(g.state.level).regions));g.state.mode='playing';h.state.mode='playing';depart(g);depart(h);assert.equal(h.state.depth,4);assert.equal(h.state.floorSeed,g.state.floorSeed);assert.equal(JSON.stringify(h.state.map.tiles),JSON.stringify(g.state.map.tiles));});
test('old active saves without depth resume as first floor and can descend',()=>{const g=start(2),saved=JSON.parse(JSON.stringify(g.exportCampaign()));delete saved.state.depth;delete saved.state.floorSeed;const h=start();assert.equal(h.restoreCampaign(saved),true);assert.equal(h.state.depth,1);assert.equal(h.manifest.seed,saved.seed);depart(h);assert.equal(h.state.depth,2);assert.equal(h.state.level,0);});
test('general hazards block free exits without advancing time',()=>{for(const id of ['water','random-exit']){const g=start(2),s=g.state;approach(g,id);const before=s.total;s.bombs=[{x:1,y:1,due:3}];assert.equal(g.act({type:'choose',kind:'depart'}),false);s.bombs=[];s.companion={x:1,y:1,name:'lost'};assert.equal(g.act({type:'choose',kind:'depart'}),false);assert.equal(s.total,before);assert.equal(s.depth,1);}});
test('fatal priority melee resolves before descent and loses the expedition',()=>{const g=start(1),s=g.state;approach(g,'water');s.player.hp=1;s.player.armor=0;s.player.inventoryGear.clothes.armor=0;const m=g.createMonster('bat',s.player.x+1,s.player.y,991,[-1,0]);s.monsters=[m];g.planMelee(m);const seed=s.floorSeed;assert.equal(g.act({type:'choose',kind:'depart'}),true);assert.equal(s.mode,'dead');assert.equal(s.depth,1);assert.equal(s.floorSeed,seed);assert.equal(s.expedition.phase,'result');assert.equal(s.expedition.result.won,false);});
test('legacy non-card action uses the same descent rules',()=>{const g=new E(12345);g.state.mode='playing';approach(g,'water');assert.equal(g.act({type:'choose',kind:'depart'}),true);assert.equal(g.state.mode,'home');assert.equal(g.state.depth,2);});

test('next floor camp resumes the same carried deck and hides the surface chest',()=>{const g=start();depart(g);const cards=JSON.stringify(g.state.expedition.cards);g.act({type:'home-select',x:0,y:2});assert.equal(g.homeNearby(),null);g.act({type:'home-select',x:1,y:2});assert.equal(g.act({type:'interact'}),true);assert.equal(g.state.mode,'playing');assert.equal(g.state.depth,2);assert.equal(g.state.expedition.phase,'active');assert.equal(JSON.stringify(g.state.expedition.cards),cards);});


test('route dialog identifies all three exit roles and the actual next depth',()=>{const g=start();g.state.depth=4;let html='';const ui=vm.createContext({game:g,esc:String,close(){},button:label=>'<button>'+label+'</button>',open(kind,text){assert.equal(kind,'route');html=text;}});const routes=[...source.matchAll(/^function route\(\)\{.*$/gm)];vm.runInContext(routes.at(-1)[0],ui);for(const [id,label]of [['mechanical','近出口'],['water','远出口'],['random-exit','随机出口']]){approach(g,id);vm.runInContext('route()',ui);assert.ok(html.includes('第5层'));assert.ok(html.includes(label));assert.equal(html.includes('带回地表'),false);assert.equal(html.includes('data-choice="depart" disabled'),id==='mechanical');}});
test('a discovered free exit becomes an actionable next-floor task before challenge completion',()=>{const g=start();g.state.depth=3;approach(g,'water');const ui=vm.createContext({game:g,preparedCards:()=>[]});const taskStart=source.indexOf('function taskModel(){'),taskEnd=source.indexOf('function presentedObjective()',taskStart);vm.runInContext(source.slice(taskStart,taskEnd),ui);const task=vm.runInContext('taskModel()',ui);assert.match(task.title,/第4层/);assert.equal(task.x,g.state.player.x);assert.equal(task.y,g.state.player.y);assert.equal(g.state.challenge.complete,false);});

