const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(process.env.GAME_HTML||path.join(__dirname,'mine5.html'),'utf8'),ctx=vm.createContext({console});for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);if(!m[1].includes('canvas=$'))vm.runInContext(m[1],ctx);}const E=ctx.EscapeEngine,plain=v=>JSON.parse(JSON.stringify(v));
function game(n=0,seed=12345){const g=new E(seed);g.enableCards();g.startExpedition(g.campaign.preparedIds,n,0);g.unpackKit(g.state.expedition.cards.find(c=>c.id==='kit').uid);g.state.mode='playing';g.state.bombs=[];g.state.hazards=[];g.state.params.hazardStart=999999;g.tick=function(n=1){this.state.turn+=n;this.state.total+=n;};return g;}
function near(g,id){const a=g.state.sites.find(a=>a.id===id);assert(a,id);a.discovered=true;g.state.player.x=a.x;g.state.player.y=a.y;return a;}
function choose(g,id,kind){near(g,id);assert(g.act({type:'choose',kind}),kind);}
function take(g,id){choose(g,id,'chapter:take:'+id);}
test('all task supplies are physically reachable before task completion in both tide phases',()=>{for(const n of [0,1,2])for(const seed of [12345,1,98765]){const g=game(n,seed),s=g.state;assert.equal(s.challenge.itemTaskVersion,3);for(const high of [false,true]){for(const [x,y]of s.adventure.tide?.cells||[])g.tile(x,y).kind=high?'water':'floor';const home=s.sites.find(a=>a.id==='home'),reach=g.reachSet(home.x,home.y);for(const a of s.sites.filter(a=>a.taskSupply))assert(g.standingNear(reach,a),n+':'+seed+':'+a.id+':'+high);}}});
test('mine requires workshop gear, repair kit and physical track fasteners; invalid actions are free',()=>{const g=game(),s=g.state,c=s.challenge;g.setAmount('ore',99);near(g,'cart-control');let t=s.turn;assert.equal(g.act({type:'choose',kind:'chapter:cart:repair-ore'}),false);assert.equal(s.turn,t);assert.equal(g.amount('ore'),99);assert.equal(g.chapterActionCheck('chapter:start').ok,false);take(g,'task-workshop-supply');near(g,'workshop');s.lootId='workshop';s.sites.find(a=>a.id==='workshop').searched=true;assert(g.loot('quest'));choose(g,'cart-control','chapter:cart:repair-kit');assert.equal(g.taskAmount('repairKit'),0);const dur=s.player.dur;for(const r of c.trackRepairs)choose(g,r.siteId,'chapter:track:'+r.siteId);assert.equal(s.player.dur,dur);assert.equal(g.taskAmount('railFastener'),0);choose(g,'cart-control','chapter:start');s.monsters=[];let limit=c.path.length+2;while(!c.complete&&limit--){s.player.x=c.cart.x;s.player.y=c.cart.y;g.challengeTurn();}assert(c.complete);});
test('three physical seal stones match inscription once; no progress from waiting or wrong shrine',()=>{const g=game(1),s=g.state,c=s.challenge;assert.equal(c.order.length,3);choose(g,'city-inscription','chapter:read');near(g,'rune-'+c.order[0]);const turn=s.turn;assert.equal(g.act({type:'choose',kind:'chapter:rune:'+c.order[0]}),false);assert.equal(s.turn,turn);for(const id of ['hammer','lamp','wave'])take(g,'task-seal-'+id);const wrong=c.order[1];near(g,'rune-'+wrong);assert.equal(g.act({type:'choose',kind:'chapter:rune:'+wrong}),false);assert.equal(c.progress,0);for(const id of c.order)choose(g,'rune-'+id,'chapter:rune:'+id);assert(c.complete);assert.equal(c.progress,3);assert.equal(g.taskAmount('sealHammer')+g.taskAmount('sealLamp')+g.taskAmount('sealWave'),0);assert.equal(s.sites.find(a=>a.id==='city-inscription').done,false);});
test('river uses rope plus crank and locking pin at any phase, never silver or waiting',()=>{const g=game(2),s=g.state,c=s.challenge;g.setAmount('ore',99);near(g,'river-anchor-a');const turn=s.turn;assert.equal(g.act({type:'choose',kind:'chapter:anchor:a:ore'}),false);assert.equal(s.turn,turn);take(g,'task-river-rigging');take(g,'task-sluice-parts');s.turn=0;choose(g,'river-anchor-a','chapter:anchor:a:rope');choose(g,'sluice-high','chapter:sluice:high');s.turn=9;choose(g,'river-anchor-b','chapter:anchor:b:rope');choose(g,'sluice-low','chapter:sluice:low');assert(c.complete);near(g,'mechanical');s.routeChoice='mechanical';assert(g.exitCheck().ok,'stabilized exit ignores tide phase');assert.equal(g.amount('ore'),99);});
test('rescue needs rope, preparation and cleared guard, preserves companion rewards',()=>{const g=game(),s=g.state;near(g,'miner');const a=s.sites.find(a=>a.id==='miner'),guard=s.monsters.find(m=>m.id===a.rescueGuardId);assert(guard);assert.equal(g.rescueCheck('rescue').ok,false);take(g,'task-rescue-supply');near(g,'miner');assert.equal(g.rescueCheck('rescue').ok,false);g.killMonster(guard,false);const reused=g.createMonster('rat',guard.x,guard.y,guard.id);s.monsters.push(reused);assert(g.rescueNpc('rescue'));assert(a.done);assert(s.companion.npcReward);assert.equal(g.taskAmount('rescueHarness'),0);assert.equal(g.taskAmount('rescueRope'),0);});
test('reserved task items survive full bags and compact saves without source duplication',()=>{const g=game(1),s=g.state;while(g.countSlots()<15)g.receiveCard(g.makeCard('bread',3));take(g,'task-seal-hammer');assert.equal(g.taskAmount('sealHammer'),1);const save=plain(E.decodeSave(plain(E.encodeSave(g.exportCampaign())))),before=JSON.stringify(save);const h=new E(1);h.enableCards();assert(h.restoreCampaign(save));assert.equal(JSON.stringify(save),before,'restore must not mutate caller backup');assert.equal(h.taskAmount('sealHammer'),1);near(h,'task-seal-hammer');assert.equal(h.choose('chapter:take:task-seal-hammer'),false);assert.equal(h.taskAmount('sealHammer'),1);assert.match(h.taskInventoryText(),/锤纹印石/);});
test('task engine initializes on every floor and keeps current task even when optional exit is discovered',()=>{const g=game();near(g,'water');assert.equal(g.chapterTaskModel().targetId,'workshop');for(let i=0;i<5;i++){const exit=near(g,'water');assert(g.descend(exit));g.state.mode='playing';assert.equal(g.state.challenge.itemTaskVersion,3);assert(g.state.sites.some(a=>a.taskSupply));assert.equal(Object.keys(g.state.local.questItems).length,0);assert(g.chapterTaskModel().requirement);assert(g.chapterTaskModel().hint);}});

test('optional pump requires a found valve wheel and invalid turn requests are free',()=>{const g=game(),s=g.state;near(g,'pump');const t=s.turn;assert.equal(g.act({type:'choose',kind:'drain'}),false);assert.equal(s.turn,t);take(g,'task-pump-wheel');near(g,'pump');assert(g.act({type:'choose',kind:'drain'}));assert(s.local.drained);assert.equal(g.taskAmount('pumpWheel'),0);assert(s.sites.find(a=>a.id==='pump').done);});
